"""
Nova Cranelift 后端
将 LIR 转换为 Cranelift IR（.clif 格式），然后编译为原生机器码。

Cranelift 本身是 Rust 库，Python 无法直接调用。我们采用两种策略：
1. 生成 Cranelift IR 文本（.clif 格式），然后调用 clif-util 编译
2. 作为 fallback，保存 .clif 文件供后续使用
"""

import os
import platform
import subprocess
import sys
import tempfile
from typing import Dict, List

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ir.ir_nodes import (
    IRType,
    LIRBinOp,
    LIRBranch,
    LIRBuildADT,
    LIRBuildList,
    LIRBuildTuple,
    LIRCall,
    LIRData,
    LIRFieldAccess,
    LIRFunction,
    LIRIndex,
    LIRInstr,
    LIRJump,
    LIRLabel,
    LIRLoadConst,
    LIRLoadGlobal,
    LIRLoadReg,
    LIRModule,
    LIRPanic,
    LIRReturn,
    LIRStoreReg,
    LIRUnaryOp,
    NovaType,
)

# Cranelift IR 类型映射
CRANELIFT_TYPE_MAP = {
    IRType.INT: "i64",
    IRType.FLOAT: "f64",
    IRType.BOOL: "i8",
    IRType.STRING: "i64",
    IRType.UNIT: "void",
    IRType.PTR: "i64",
    IRType.CHAR: "i8",
    IRType.LIST: "i64",
    IRType.MAP: "i64",
    IRType.TUPLE: "i64",
    IRType.FUNCTION: "i64",
    IRType.ADT: "i64",
    IRType.NEVER: "void",
    IRType.TYPE_VAR: "i64",
}


class CraneliftBackend:
    """将 Nova LIR 转换为 Cranelift IR"""

    def __init__(self):
        self.output_lines: List[str] = []
        self.indent_level = 0
        self.temp_counter = 0
        self.clif_types: Dict[str, str] = {}  # SSA 名 -> 类型

    def compile(self, lir_module: LIRModule) -> str:
        """将 LIR Module 编译为 Cranelift IR 文本"""
        self.output_lines = []
        self.temp_counter = 0
        self.clif_types = {}

        self._emit_header()

        # 数据段
        for global_var in lir_module.globals:
            if global_var.data:
                self._emit_data(global_var.data)

        for data in lir_module.data_section:
            self._emit_data(data)

        # 编译每个函数
        for name, func in lir_module.functions.items():
            self._compile_function(func)

        return "\n".join(self.output_lines)

    def _emit(self, line: str = ""):
        indent = "    " * self.indent_level
        self.output_lines.append(indent + line)

    def _emit_header(self):
        self._emit("; Generated by Nova Cranelift Backend")
        self._emit(f"; Target: {self._detect_target()}")
        self._emit("")
        self._emit(f"target {self._detect_target()}")
        self._emit("")

    def _detect_target(self) -> str:
        machine = platform.machine().lower()
        if machine in ("x86_64", "amd64"):
            return "x86_64"
        elif machine in ("aarch64", "arm64"):
            return "aarch64"
        elif "riscv" in machine:
            return "riscv64"
        return "x86_64"

    def _nova_type_to_clif(self, ty: NovaType) -> str:
        return CRANELIFT_TYPE_MAP.get(ty.kind, "i64")

    def _new_temp(self) -> str:
        name = f"v{self.temp_counter}"
        self.temp_counter += 1
        return name

    def _compile_function(self, func: LIRFunction):
        params = ", ".join(
            f"{self._nova_type_to_clif(ty)} ${loc}" for loc, ty in func.params
        )
        ret = self._nova_type_to_clif(func.return_type)

        if ret == "void":
            self._emit(f"function %nova_{func.name}({params}) {{")
        else:
            self._emit(f"function %nova_{func.name}({params}) -> {ret} {{")
        self.indent_level += 1

        # 栈帧分配
        if func.stack_size > 0:
            self._emit(f"; stack_frame_size = {func.stack_size}")

        # 编译指令
        for instr in func.body:
            self._compile_instr(instr, func)

        # 确保有 return
        if not func.body or not any(isinstance(i, LIRReturn) for i in func.body):
            self._emit("return")

        self.indent_level -= 1
        self._emit("}")
        self._emit("")

    def _compile_instr(self, instr: LIRInstr, func: LIRFunction):
        if isinstance(instr, LIRLabel):
            self._emit(f"{instr.name}:")

        elif isinstance(instr, LIRLoadConst):
            self._emit_load_const(instr)

        elif isinstance(instr, LIRLoadGlobal):
            self._emit(f"v{self._new_temp()} = symbol_value @{instr.global_name}")

        elif isinstance(instr, LIRBinOp):
            self._emit_binop(instr)

        elif isinstance(instr, LIRUnaryOp):
            self._emit_unaryop(instr)

        elif isinstance(instr, LIRCall):
            self._emit_call(instr)

        elif isinstance(instr, LIRReturn):
            self._emit("return")

        elif isinstance(instr, LIRJump):
            self._emit(f"jump {instr.target}")

        elif isinstance(instr, LIRBranch):
            if instr.src_locs:
                cond_loc = instr.src_locs[0][0] if instr.src_locs else "v0"
            else:
                cond_loc = "v0"
            self._emit(f"brz {cond_loc}, block_false")
            self._emit(f"jump block_true")

        elif isinstance(instr, LIRBuildList):
            self._emit(
                f"v{self._new_temp()} = call $nova_list_new(i64.const {instr.count})"
            )

        elif isinstance(instr, LIRBuildTuple):
            size = instr.count * 8
            self._emit(f"v{self._new_temp()} = call $nova_alloc(i64.const {size})")

        elif isinstance(instr, LIRBuildADT):
            tag = instr.type_tag
            fields_size = instr.field_count * 8 + 8
            self._emit(
                f"v{self._new_temp()} = call $nova_alloc(i64.const {fields_size})"
            )

        elif isinstance(instr, LIRFieldAccess):
            offset = instr.offset
            src_loc = instr.src_locs[0][0] if instr.src_locs else "v0"
            self._emit(f"v{self._new_temp()} = load i64, {src_loc} + {offset}")

        elif isinstance(instr, LIRIndex):
            self._emit(f"v{self._new_temp()} = load i64, v0 + 0")

        elif isinstance(instr, LIRPanic):
            self._emit("trap unreachable")

        elif isinstance(instr, LIRLoadReg):
            if instr.src_locs and instr.dst_loc:
                src = instr.src_locs[0][0]
                dst = instr.dst_loc[0]
                self._emit(f"v{self._new_temp()} = copy {src}")

        elif isinstance(instr, LIRStoreReg):
            pass

    def _emit_load_const(self, instr: LIRLoadConst):
        if instr.const_type == "int":
            self._emit(f"v{self._new_temp()} = iconst {instr.value}")
        elif instr.const_type == "float":
            self._emit(f"v{self._new_temp()} = f64.const {repr(instr.value)}")
        elif instr.const_type == "bool":
            val = 1 if instr.value else 0
            self._emit(f"v{self._new_temp()} = iconst {val}")
        elif instr.const_type == "string":
            self._emit(f"v{self._new_temp()} = symbol_value @str_{self._new_temp()}")
        elif instr.const_type == "closure":
            self._emit(f"v{self._new_temp()} = iconst 0")
        # unit: 不生成指令

    def _emit_binop(self, instr: LIRBinOp):
        int_op_map = {
            "+": "iadd",
            "-": "isub",
            "*": "imul",
            "/": "sdiv",
            "%": "srem",
            "&": "band",
            "|": "bor",
            "^": "bxor",
            "<<": "ishl",
            ">>": "sshr",
            "==": "icmp eq",
            "!=": "icmp ne",
            "<": "icmp slt",
            ">": "icmp sgt",
            "<=": "icmp sle",
            ">=": "icmp sge",
        }
        float_op_map = {
            "+": "fadd",
            "-": "fsub",
            "*": "fmul",
            "/": "fdiv",
            "==": "fcmp eq",
            "!=": "fcmp ne",
            "<": "fcmp lt",
            ">": "fcmp gt",
            "<=": "fcmp le",
            ">=": "fcmp ge",
        }

        op = int_op_map.get(instr.op, "iadd")
        left = instr.src_locs[0][0] if instr.src_locs else "v0"
        right = instr.src_locs[1][0] if len(instr.src_locs) > 1 else "v0"

        self._emit(f"v{self._new_temp()} = {op} {left}, {right}")

    def _emit_unaryop(self, instr: LIRUnaryOp):
        operand = instr.src_locs[0][0] if instr.src_locs else "v0"
        if instr.op == "-":
            self._emit(f"v{self._new_temp()} = ineg {operand}")
        elif instr.op == "!":
            self._emit(f"v{self._new_temp()} = icmp eq {operand}, 0")

    def _emit_call(self, instr: LIRCall):
        func_ref = f"$nova_{instr.func_name}"
        arg_str = ", ".join(f"i64 {loc}" for loc, _ in (instr.src_locs or []))
        if arg_str:
            self._emit(f"v{self._new_temp()} = call {func_ref}({arg_str})")
        else:
            self._emit(f"call {func_ref}()")

    def _emit_data(self, data: LIRData):
        self._emit(f"section .rodata")
        hex_str = " ".join(f"0x{b:02x}" for b in data.value)
        self._emit(f"@{data.name} = {{ {hex_str} }}")
        self._emit("")

    def compile_to_object(
        self, lir_module: LIRModule, output_path: str, optimize: str = "speed"
    ) -> str:
        """编译 LIR 为目标文件"""
        clif_ir = self.compile(lir_module)

        # 写入临时 .clif 文件
        with tempfile.NamedTemporaryFile(suffix=".clif", mode="w", delete=False) as f:
            f.write(clif_ir)
            clif_path = f.name

        try:
            # 尝试调用 cranelift CLI 编译
            result = subprocess.run(
                [
                    "clif-util",
                    "compile",
                    "--optimize",
                    optimize,
                    "-o",
                    output_path,
                    clif_path,
                ],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode != 0:
                raise RuntimeError(f"Cranelift compile failed: {result.stderr}")
        except FileNotFoundError:
            # Cranelift CLI 不可用，保存 .clif 文件
            return self._fallback_to_c(lir_module, output_path, clif_ir)
        finally:
            os.unlink(clif_path)

        return output_path

    def _fallback_to_c(
        self, lir_module: LIRModule, output_path: str, clif_ir: str = ""
    ) -> str:
        """Fallback：当 Cranelift CLI 不可用时，保存 .clif 文件"""
        clif_output = output_path + ".clif"
        with open(clif_output, "w") as f:
            f.write(clif_ir or self.compile(lir_module))
        return clif_output
