"""
Nova Cranelift 后端（已弃用）

.. deprecated:: v0.3.x
    根据 ARCHITECTURE_VISION.md 第 2.3 节「立即架构手术 C」，
    Cranelift 后端已正式弃用，将在 v0.5.0 版本中移除。

    **推荐替代方案：**
    - Native x86_64 后端（`backend/native_backend.py`）：直接生成 ELF
    - C 后端（`backend/lir_c_backend.py`）：LIR → C → GCC/Clang 编译
    - WasmGC 后端（`backend/wasm_backend.py`）：输出 WasmGC 字节码

弃用原因（2026-07-29 架构战略决策）：
1. 功能严重残缺：_compile_index 硬编码 v0+0、闭包支持仅 iconst 0 占位
2. 0 端到端测试覆盖：仅 4 个存在性测试，无算术/控制流/数据结构断言
3. 无法自举：Python 侧无法直接调用 Rust 库（clif-util 外部依赖）
4. 维护成本 > 收益：3 条活跃后端路径已足够覆盖编译目标

原功能简述（仅供历史参考）：
将 LIR 转换为 Cranelift IR（.clif 格式），然后编译为原生机器码。
Cranelift 本身是 Rust 库，Python 无法直接调用。原采用两种策略：
1. 生成 Cranelift IR 文本（.clif 格式），然后调用 clif-util 编译
2. 作为 fallback，保存 .clif 文件供后续使用
"""

import os
import platform
import subprocess
import tempfile
import warnings
from typing import Dict, List

from ..ir.ir_nodes import (
    IRType,
    LIRBinOp,
    LIRBranch,
    LIRBuildADT,
    LIRBuildList,
    LIRBuildMap,
    LIRBuildTuple,
    LIRCall,
    LIRData,
    LIRFieldAccess,
    LIRFunction,
    LIRIndex,
    LIRInstr,
    LIRJump,
    LIRLabel,
    LIRLoadConst,
    LIRLoadGlobal,
    LIRLoadReg,
    LIRModule,
    LIRPanic,
    LIRReturn,
    LIRStoreReg,
    LIRUnaryOp,
    NovaType,
)

# ---------------------------------------------------------------------------
# Cranelift IR 类型映射（已弃用，保留至 v0.5.0 以兼容旧代码）
# ---------------------------------------------------------------------------

#: Cranelift IR 类型映射表（Nova IRType → Cranelift 类型字符串）
#:
#: .. deprecated:: v0.3.x
#:     整个 Cranelift 后端已弃用，此常量将随其后端一同移除。
#:     请使用 Native/C/WasmGC 后端的对应类型映射。
CRANELIFT_TYPE_MAP: Dict = {
    IRType.INT: "i64",
    IRType.FLOAT: "f64",
    IRType.BOOL: "i8",
    IRType.STRING: "i64",
    IRType.UNIT: "void",
    IRType.PTR: "i64",
    IRType.CHAR: "i8",
    IRType.LIST: "i64",
    IRType.MAP: "i64",
    IRType.TUPLE: "i64",
    IRType.FUNCTION: "i64",
    IRType.ADT: "i64",
    IRType.NEVER: "void",
    IRType.TYPE_VAR: "i64",
}


class CraneliftBackend:
    """将 Nova LIR 转换为 Cranelift IR（已弃用）

    .. deprecated:: v0.3.x
        根据 ARCHITECTURE_VISION.md 第 2.3 节立即架构手术 C，
        本类已正式弃用，将在 v0.5.0 版本中移除。

        请迁移至以下受支持的后端之一：
        - :class:`nova.backend.native_backend.NativeCodeGen` — x86_64 ELF 原生
        - :class:`nova.backend.lir_c_backend.LIRCBackend` — C 源码生成（GCC/Clang）
        - :class:`nova.backend.wasm_backend.WasmGCBackend` — WasmGC 字节码

    实例化时会触发 :exc:`DeprecationWarning`。
    """

    def __init__(self):
        # 立即架构手术 C：Cranelift 后端已弃用，v0.5.0 移除
        # 参考：ARCHITECTURE_VISION.md §2.3
        warnings.warn(
            "CraneliftBackend 已弃用（Nova v0.3.x → v0.5.0 移除）。\n"
            "  弃用原因：功能残缺（索引/闭包 stub）、0 端到端测试、\n"
            "          无法自举（需外部 Rust clif-util）、维护成本 > 收益。\n"
            "  推荐替代：\n"
            "    • Native x86_64  → nova.backend.native_backend.NativeCodeGen\n"
            "    • C 源码编译    → nova.backend.lir_c_backend.LIRCBackend\n"
            "    • WasmGC 字节码 → nova.backend.wasm_backend.WasmGCBackend\n"
            "  参考文档：ARCHITECTURE_VISION.md §2.3「立即架构手术 C」",
            DeprecationWarning,
            stacklevel=2,
        )
        self.output_lines: List[str] = []
        self.indent_level = 0
        self.temp_counter = 0
        self.clif_types: Dict[str, str] = {}  # SSA 名 -> 类型
        self._instr_dispatch = self._build_instr_dispatch_table()

    def compile(self, lir_module: LIRModule) -> str:
        """将 LIR Module 编译为 Cranelift IR 文本（已弃用方法）

        .. deprecated:: v0.3.x
            请使用受支持后端的对应编译方法。
        """
        self.output_lines = []
        self.temp_counter = 0
        self.clif_types = {}

        self._emit_header()

        # 数据段
        for global_var in lir_module.globals:
            if global_var.data:
                self._emit_data(global_var.data)

        for data in lir_module.data_section:
            self._emit_data(data)

        # 编译每个函数
        for name, func in lir_module.functions.items():
            self._compile_function(func)

        return "\n".join(self.output_lines)

    def _emit(self, line: str = ""):
        indent = "    " * self.indent_level
        self.output_lines.append(indent + line)

    def _emit_header(self):
        self._emit("; Generated by Nova Cranelift Backend")
        self._emit(f"; Target: {self._detect_target()}")
        self._emit("")
        self._emit(f"target {self._detect_target()}")
        self._emit("")

    def _detect_target(self) -> str:
        machine = platform.machine().lower()
        if machine in ("x86_64", "amd64"):
            return "x86_64"
        elif machine in ("aarch64", "arm64"):
            return "aarch64"
        elif "riscv" in machine:
            return "riscv64"
        return "x86_64"

    def _nova_type_to_clif(self, ty: NovaType) -> str:
        return CRANELIFT_TYPE_MAP.get(ty.kind, "i64")

    def _new_temp(self) -> str:
        name = f"v{self.temp_counter}"
        self.temp_counter += 1
        return name

    def _compile_function(self, func: LIRFunction):
        params = ", ".join(
            f"{self._nova_type_to_clif(ty)} ${loc}" for loc, ty in func.params
        )
        ret = self._nova_type_to_clif(func.return_type)

        if ret == "void":
            self._emit(f"function %nova_{func.name}({params}) {{")
        else:
            self._emit(f"function %nova_{func.name}({params}) -> {ret} {{")
        self.indent_level += 1

        # 栈帧分配
        if func.stack_size > 0:
            self._emit(f"; stack_frame_size = {func.stack_size}")

        # 编译指令
        for instr in func.body:
            self._compile_instr(instr, func)

        # 确保有 return
        if not func.body or not any(isinstance(i, LIRReturn) for i in func.body):
            self._emit("return")

        self.indent_level -= 1
        self._emit("}")
        self._emit("")

    def _build_instr_dispatch_table(self) -> dict:
        """构建 LIR 指令类型 → 编译方法 的调度表

        使用类型 → 方法 的调度表模式替代长 if-isinstance 链，
        圈复杂度从 ~24 降至 ~3，提升可维护性和可扩展性。
        """
        return {
            # 标签
            LIRLabel: self._compile_label,
            # 常量与加载
            LIRLoadConst: self._compile_load_const,
            LIRLoadGlobal: self._compile_load_global,
            LIRLoadReg: self._compile_load_reg,
            LIRStoreReg: self._compile_store_reg,
            # 运算
            LIRBinOp: self._compile_binop,
            LIRUnaryOp: self._compile_unaryop,
            # 函数调用
            LIRCall: self._compile_call,
            # 控制流
            LIRReturn: self._compile_return,
            LIRJump: self._compile_jump,
            LIRBranch: self._compile_branch,
            # 数据结构构建
            LIRBuildList: self._compile_build_list,
            LIRBuildMap: self._compile_build_map,
            LIRBuildTuple: self._compile_build_tuple,
            LIRBuildADT: self._compile_build_adt,
            # 访问
            LIRFieldAccess: self._compile_field_access,
            LIRIndex: self._compile_index,
            # 杂项
            LIRPanic: self._compile_panic,
        }

    def _compile_instr(self, instr: LIRInstr, func: LIRFunction):
        """编译单条 LIR 指令（调度表分发）

        使用类型 → 方法 的调度表模式替代长 if-isinstance 链，
        圈复杂度从 ~24 降至 ~3。
        """
        handler = self._instr_dispatch.get(type(instr))
        if handler:
            handler(instr)
        else:
            raise NotImplementedError(
                f"Cranelift 后端尚未实现指令: {type(instr).__name__}"
            )

    # ---- 各指令类型的独立编译方法 ----

    def _compile_label(self, instr: LIRLabel):
        """编译标签"""
        self._emit(f"{instr.name}:")

    def _compile_load_const(self, instr: LIRLoadConst):
        """编译常量加载"""
        self._emit_load_const(instr)

    def _compile_load_global(self, instr: LIRLoadGlobal):
        """编译全局变量加载"""
        self._emit(f"v{self._new_temp()} = symbol_value @{instr.global_name}")

    def _compile_binop(self, instr: LIRBinOp):
        """编译二元运算"""
        self._emit_binop(instr)

    def _compile_unaryop(self, instr: LIRUnaryOp):
        """编译一元运算"""
        self._emit_unaryop(instr)

    def _compile_call(self, instr: LIRCall):
        """编译函数调用"""
        self._emit_call(instr)

    def _compile_return(self, instr: LIRReturn):
        """编译返回指令"""
        self._emit("return")

    def _compile_jump(self, instr: LIRJump):
        """编译无条件跳转"""
        self._emit(f"jump {instr.target}")

    def _compile_branch(self, instr: LIRBranch):
        """编译条件分支"""
        if instr.src_locs:
            cond_loc = instr.src_locs[0][0] if instr.src_locs else "v0"
        else:
            cond_loc = "v0"
        false_target = instr.false_target or "block_false"
        true_target = instr.true_target or "block_true"
        self._emit(f"brz {cond_loc}, {false_target}")
        self._emit(f"jump {true_target}")

    def _compile_build_list(self, instr: LIRBuildList):
        """编译列表构建"""
        self._emit(
            f"v{self._new_temp()} = call $nova_list_new(i64.const {instr.count})"
        )

    def _compile_build_map(self, instr: LIRBuildMap):
        """编译 Map 构建"""
        self._emit(
            f"v{self._new_temp()} = call $nova_map_new(i64.const {instr.entry_count})"
        )

    def _compile_build_tuple(self, instr: LIRBuildTuple):
        """编译元组构建"""
        size = instr.count * 8
        self._emit(f"v{self._new_temp()} = call $nova_alloc(i64.const {size})")

    def _compile_build_adt(self, instr: LIRBuildADT):
        """编译 ADT 构建"""
        tag = instr.type_tag
        fields_size = instr.field_count * 8 + 8
        self._emit(
            f"v{self._new_temp()} = call $nova_alloc(i64.const {fields_size})"
        )

    def _compile_field_access(self, instr: LIRFieldAccess):
        """编译字段访问"""
        offset = instr.offset
        src_loc = instr.src_locs[0][0] if instr.src_locs else "v0"
        self._emit(f"v{self._new_temp()} = load i64, {src_loc} + {offset}")

    def _compile_index(self, instr: LIRIndex):
        """编译索引访问"""
        self._emit(f"v{self._new_temp()} = load i64, v0 + 0")

    def _compile_panic(self, instr: LIRPanic):
        """编译 panic / unreachable trap"""
        self._emit("trap unreachable")

    def _compile_load_reg(self, instr: LIRLoadReg):
        """编译寄存器加载"""
        if instr.src_locs and instr.dst_loc:
            src = instr.src_locs[0][0]
            dst = instr.dst_loc[0]
            self._emit(f"v{self._new_temp()} = copy {src}")

    def _compile_store_reg(self, instr: LIRStoreReg):
        """编译寄存器存储（Cranelift 后端无操作）"""
        pass

    def _emit_load_const(self, instr: LIRLoadConst):
        if instr.const_type == "int":
            self._emit(f"v{self._new_temp()} = iconst {instr.value}")
        elif instr.const_type == "float":
            self._emit(f"v{self._new_temp()} = f64.const {repr(instr.value)}")
        elif instr.const_type == "bool":
            val = 1 if instr.value else 0
            self._emit(f"v{self._new_temp()} = iconst {val}")
        elif instr.const_type == "string":
            self._emit(f"v{self._new_temp()} = symbol_value @str_{self._new_temp()}")
        elif instr.const_type == "closure":
            self._emit(f"v{self._new_temp()} = iconst 0")
        # unit: 不生成指令

    def _emit_binop(self, instr: LIRBinOp):
        int_op_map = {
            "+": "iadd",
            "-": "isub",
            "*": "imul",
            "/": "sdiv",
            "%": "srem",
            "&": "band",
            "|": "bor",
            "^": "bxor",
            "<<": "ishl",
            ">>": "sshr",
            "==": "icmp eq",
            "!=": "icmp ne",
            "<": "icmp slt",
            ">": "icmp sgt",
            "<=": "icmp sle",
            ">=": "icmp sge",
        }
        float_op_map = {
            "+": "fadd",
            "-": "fsub",
            "*": "fmul",
            "/": "fdiv",
            "==": "fcmp eq",
            "!=": "fcmp ne",
            "<": "fcmp lt",
            ">": "fcmp gt",
            "<=": "fcmp le",
            ">=": "fcmp ge",
        }

        op = int_op_map.get(instr.op, "iadd")
        left = instr.src_locs[0][0] if instr.src_locs else "v0"
        right = instr.src_locs[1][0] if len(instr.src_locs) > 1 else "v0"

        self._emit(f"v{self._new_temp()} = {op} {left}, {right}")

    def _emit_unaryop(self, instr: LIRUnaryOp):
        operand = instr.src_locs[0][0] if instr.src_locs else "v0"
        if instr.op == "-":
            self._emit(f"v{self._new_temp()} = ineg {operand}")
        elif instr.op == "!":
            self._emit(f"v{self._new_temp()} = icmp eq {operand}, 0")

    def _emit_call(self, instr: LIRCall):
        func_ref = f"$nova_{instr.func_name}"
        arg_str = ", ".join(f"i64 {loc}" for loc, _ in (instr.src_locs or []))
        if arg_str:
            self._emit(f"v{self._new_temp()} = call {func_ref}({arg_str})")
        else:
            self._emit(f"call {func_ref}()")

    def _emit_data(self, data: LIRData):
        self._emit(f"section .rodata")
        hex_str = " ".join(f"0x{b:02x}" for b in data.value)
        self._emit(f"@{data.name} = {{ {hex_str} }}")
        self._emit("")

    def compile_to_object(
        self, lir_module: LIRModule, output_path: str, optimize: str = "speed"
    ) -> str:
        """编译 LIR 为目标文件（已弃用方法）

        .. deprecated:: v0.3.x
            请使用受支持后端的对应编译方法。
        """
        clif_ir = self.compile(lir_module)

        # 写入临时 .clif 文件
        with tempfile.NamedTemporaryFile(suffix=".clif", mode="w", delete=False) as f:
            f.write(clif_ir)
            clif_path = f.name

        try:
            # 尝试调用 cranelift CLI 编译
            result = subprocess.run(
                [
                    "clif-util",
                    "compile",
                    "--optimize",
                    optimize,
                    "-o",
                    output_path,
                    clif_path,
                ],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode != 0:
                raise RuntimeError(f"Cranelift compile failed: {result.stderr}")
        except FileNotFoundError:
            # Cranelift CLI 不可用，保存 .clif 文件
            return self._fallback_to_c(lir_module, output_path, clif_ir)
        finally:
            os.unlink(clif_path)

        return output_path

    def _fallback_to_c(
        self, lir_module: LIRModule, output_path: str, clif_ir: str = ""
    ) -> str:
        """Fallback：当 Cranelift CLI 不可用时，保存 .clif 文件"""
        clif_output = output_path + ".clif"
        with open(clif_output, "w") as f:
            f.write(clif_ir or self.compile(lir_module))
        return clif_output
