"""
Nova WasmGC 后端
将 LIR 转换为 WebAssembly 文本格式（WAT），支持 GC 提案。
"""

from typing import List, Dict, Optional, Tuple
import os
import subprocess
import sys

import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ir.ir_nodes import (
    LIRModule,
    LIRFunction,
    LIRGlobal,
    LIRData,
    LIRInstr,
    LIRLoadConst,
    LIRLoadGlobal,
    LIRStoreGlobal,
    LIRLoadReg,
    LIRStoreReg,
    LIRBinOp,
    LIRUnaryOp,
    LIRCall,
    LIRCallIndirect,
    LIRJump,
    LIRBranch,
    LIRReturn,
    LIRLabel,
    LIRIndex,
    LIRFieldAccess,
    LIRBuildList,
    LIRBuildTuple,
    LIRBuildADT,
    LIRPanic,
    IRType,
    NovaType,
    INT_TYPE,
    FLOAT_TYPE,
    STRING_TYPE,
    BOOL_TYPE,
    UNIT_TYPE,
)

# Wasm 类型映射
WASM_TYPE_MAP = {
    IRType.INT: "i64",
    IRType.FLOAT: "f64",
    IRType.BOOL: "i32",
    IRType.STRING: "i32",
    IRType.UNIT: "",
    IRType.PTR: "i32",
    IRType.CHAR: "i32",
    IRType.LIST: "i32",
    IRType.MAP: "i32",
    IRType.TUPLE: "i32",
    IRType.FUNCTION: "i32",
    IRType.ADT: "i32",
    IRType.NEVER: "",
    IRType.TYPE_VAR: "i32",
}


class WasmGCBackend:
    """将 Nova LIR 编译为 WebAssembly（WasmGC）"""

    def __init__(self):
        self.output_lines: List[str] = []
        self.indent_level = 0
        self.string_table: Dict[str, int] = {}  # 字符串 -> 数据段偏移
        self.string_counter = 0

    def compile(self, lir_module: LIRModule) -> str:
        """将 LIR Module 编译为 WAT（WebAssembly Text Format）"""
        self.output_lines = []
        self.string_table = {}
        self.string_counter = 0

        # 预扫描字符串常量
        self._scan_strings(lir_module)

        self._emit_header()
        self._emit_types()
        self._emit_imports()
        self._emit_memory()
        self._emit_string_data()
        self._emit_functions(lir_module)
        self._emit_start_function(lir_module)

        return "\n".join(self.output_lines)

    def _emit(self, line: str = ""):
        indent = "  " * self.indent_level
        self.output_lines.append(indent + line)

    def _emit_header(self):
        self._emit("(;; Generated by Nova WasmGC Backend ;;)")
        self._emit("(;; Supports WasmGC (Garbage Collection) Proposal ;;)")
        self._emit("")
        self._emit("(module $nova")
        self.indent_level += 1

    def _nova_type_to_wasm(self, ty: NovaType) -> str:
        return WASM_TYPE_MAP.get(ty.kind, "i32")

    def _emit_types(self):
        """定义 GC struct 类型（对应 Nova 的 ADT）"""
        self._emit(";; ---- GC 类型定义 ----")
        self._emit("")

        # Option[T] - None
        self._emit("(type $option_none (struct (field $tag i32)))")
        # Option[T] - Some
        self._emit("(type $option_some (struct (field $tag i32) (field $value i64)))")
        self._emit("")

        # Result[T, E] - Ok
        self._emit("(type $result_ok (struct (field $tag i32) (field $value i64)))")
        # Result[T, E] - Err
        self._emit("(type $result_err (struct (field $tag i32) (field $error i64)))")
        self._emit("")

        # 列表 struct（WasmGC struct 类型）
        self._emit("(type $nova_list (struct")
        self.indent_level += 1
        self._emit("(field $length i32)")
        self._emit("(field $capacity i32)")
        self._emit("(field $data i32)")
        self.indent_level -= 1
        self._emit(")")
        self._emit("")

    def _emit_imports(self):
        """导入运行时函数"""
        self._emit(";; ---- 运行时函数导入 ----")
        self._emit("")

        runtime_imports = [
            ('"nova_print"', "(func $nova_print (param i32))"),
            ('"nova_print_int"', "(func $nova_print_int (param i64))"),
            ('"nova_print_float"', "(func $nova_print_float (param f64))"),
            (
                '"nova_string_concat"',
                "(func $nova_string_concat (param i32) (param i32) (result i32))",
            ),
            ('"nova_list_new"', "(func $nova_list_new (param i32) (result i32))"),
            ('"nova_list_push"', "(func $nova_list_push (param i32) (param i64))"),
            (
                '"nova_list_get"',
                "(func $nova_list_get (param i32) (param i32) (result i64))",
            ),
            ('"nova_list_length"', "(func $nova_list_length (param i32) (result i32))"),
            ('"nova_sqrt"', "(func $nova_sqrt (param f64) (result f64))"),
            ('"nova_sin"', "(func $nova_sin (param f64) (result f64))"),
            ('"nova_cos"', "(func $nova_cos (param f64) (result f64))"),
            ('"nova_pow"', "(func $nova_pow (param f64) (param f64) (result f64))"),
            ('"nova_abs"', "(func $nova_abs (param f64) (result f64))"),
            ('"nova_floor"', "(func $nova_floor (param f64) (result f64))"),
            ('"nova_ceil"', "(func $nova_ceil (param f64) (result f64))"),
            ('"nova_round"', "(func $nova_round (param f64) (result f64))"),
            ('"nova_alloc"', "(func $nova_alloc (param i32) (result i32))"),
            ('"nova_free"', "(func $nova_free (param i32))"),
            ('"nova_init"', "(func $nova_init)"),
            ('"nova_cleanup"', "(func $nova_cleanup)"),
            ('"nova_json_parse"', "(func $nova_json_parse (param i32) (result i32))"),
            (
                '"nova_json_stringify"',
                "(func $nova_json_stringify (param i32) (result i32))",
            ),
            ('"nova_panic"', "(func $nova_panic (param i32))"),
        ]

        for name, sig in runtime_imports:
            self._emit(f'(import "nova_runtime" {name} {sig})')
        self._emit("")

    def _emit_memory(self):
        """声明线性内存"""
        self._emit(";; ---- 内存 ----")
        self._emit('(memory (export "memory") 100)')
        self._emit("")

    def _scan_strings(self, lir_module: LIRModule):
        """预扫描 LIR 中的字符串常量"""
        offset = 0
        for func in lir_module.functions.values():
            for instr in func.body:
                if isinstance(instr, LIRLoadConst) and instr.const_type == "string":
                    if instr.value not in self.string_table:
                        self.string_table[instr.value] = offset
                        encoded = str(instr.value).encode("utf-8") + b"\\x00"
                        offset += len(encoded)

    def _emit_string_data(self):
        """输出字符串数据段"""
        self._emit(";; ---- 数据段 ----")
        if not self.string_table:
            self._emit("")
            return

        # 将所有字符串编码到一个数据段
        for string_val, offset in self.string_table.items():
            escaped = self._escape_wat_string(str(string_val))
            self._emit(f'(data (i32.const {offset}) "{escaped}\\00")')
        self._emit("")

    def _escape_wat_string(self, s: str) -> str:
        """转义字符串为 WAT 格式"""
        result = []
        for ch in s:
            if ch == '"':
                result.append('\\"')
            elif ch == "\\":
                result.append("\\\\")
            elif ch == "\n":
                result.append("\\n")
            elif ch == "\t":
                result.append("\\t")
            elif ch == "\r":
                result.append("\\r")
            elif 0x20 <= ord(ch) < 0x7F:
                result.append(ch)
            else:
                result.append(f"\\{ord(ch):02x}")
        return "".join(result)

    def _emit_functions(self, lir_module: LIRModule):
        """编译所有函数"""
        self._emit(";; ---- 函数定义 ----")
        self._emit("")

        for name, func in lir_module.functions.items():
            self._compile_function(name, func)

    def _compile_function(self, name: str, func: LIRFunction):
        params_parts = []
        for loc, ty in func.params:
            wasm_ty = self._nova_type_to_wasm(ty)
            if wasm_ty:
                params_parts.append(f"(param ${loc} {wasm_ty})")
        params_str = " ".join(params_parts)

        ret_ty = self._nova_type_to_wasm(func.return_type)
        result_str = f"(result {ret_ty})" if ret_ty else ""

        self._emit(f"(func $nova_{name} {params_str} {result_str}")
        self._emit("{")

        self.indent_level += 1

        # 编译指令
        for instr in func.body:
            self._compile_instr(instr, func)

        self.indent_level -= 1
        self._emit(")")
        self._emit("")

    def _compile_instr(self, instr: LIRInstr, func: LIRFunction):
        if isinstance(instr, LIRLabel):
            self._emit(f"(block $block_{instr.name}")
            self.indent_level += 1

        elif isinstance(instr, LIRLoadConst):
            self._emit_load_const(instr)

        elif isinstance(instr, LIRBinOp):
            self._emit_binop(instr)

        elif isinstance(instr, LIRUnaryOp):
            if instr.op == "-":
                if instr.src_locs:
                    src_ty = instr.src_locs[0][1] if instr.src_locs else INT_TYPE
                    if src_ty.kind == IRType.FLOAT:
                        self._emit("(f64.neg)")
                    else:
                        self._emit("(i64.neg)")
            elif instr.op == "!":
                self._emit("(i32.eqz)")

        elif isinstance(instr, LIRCall):
            self._emit_call(instr)

        elif isinstance(instr, LIRReturn):
            self._emit("(return)")

        elif isinstance(instr, LIRJump):
            self._emit(f"(br $block_{instr.target})")

        elif isinstance(instr, LIRBranch):
            if instr.src_locs:
                self._emit(f"(local.get ${instr.src_locs[0][0]})")
            self._emit("(br_if $block_false)")

        elif isinstance(instr, LIRBuildList):
            self._emit(f"(i32.const {instr.count})")
            self._emit("(call $nova_list_new)")

        elif isinstance(instr, LIRBuildTuple):
            self._emit(f"(i32.const {instr.count * 8})")
            self._emit("(call $nova_alloc)")

        elif isinstance(instr, LIRBuildADT):
            self._emit(f"(i32.const {instr.type_tag})")
            self._emit(f"(i32.const {instr.field_count * 8 + 8})")
            self._emit("(call $nova_alloc)")

        elif isinstance(instr, LIRFieldAccess):
            offset = instr.offset
            self._emit(f"(i32.const {offset})")
            self._emit("(i32.add)")
            self._emit("(i64.load align=8)")

        elif isinstance(instr, LIRIndex):
            self._emit("(i64.load align=8)")

        elif isinstance(instr, LIRPanic):
            self._emit("(i32.const 0)")
            self._emit("(call $nova_panic)")
            self._emit("(unreachable)")

        elif isinstance(instr, LIRLoadReg):
            if instr.src_locs:
                self._emit(f"(local.get ${instr.src_locs[0][0]})")

        elif isinstance(instr, LIRStoreReg):
            pass

    def _emit_load_const(self, instr: LIRLoadConst):
        if instr.const_type == "int":
            self._emit(f"(i64.const {instr.value})")
        elif instr.const_type == "float":
            self._emit(f"(f64.const {repr(instr.value)})")
        elif instr.const_type == "bool":
            self._emit(f"(i32.const {1 if instr.value else 0})")
        elif instr.const_type == "string":
            offset = self._get_string_offset(str(instr.value))
            self._emit(f"(i32.const {offset})")
        elif instr.const_type == "closure":
            self._emit("(i32.const 0)")
        # unit: 无值

    def _emit_binop(self, instr: LIRBinOp):
        op_map = {
            "+": ("i64.add", "f64.add"),
            "-": ("i64.sub", "f64.sub"),
            "*": ("i64.mul", "f64.mul"),
            "/": ("i64.div_s", "f64.div"),
            "%": ("i64.rem_s", ""),
            "==": ("i64.eq", "f64.eq"),
            "!=": ("i64.ne", "f64.ne"),
            "<": ("i64.lt_s", "f64.lt"),
            ">": ("i64.gt_s", "f64.gt"),
            "<=": ("i64.le_s", "f64.le"),
            ">=": ("i64.ge_s", "f64.ge"),
        }

        int_op, float_op = op_map.get(instr.op, ("i64.add", "f64.add"))

        # 检查是否是浮点操作
        is_float = False
        if instr.src_locs:
            src_ty = instr.src_locs[0][1] if instr.src_locs else INT_TYPE
            if src_ty.kind == IRType.FLOAT:
                is_float = True

        if is_float and float_op:
            self._emit(f"({float_op})")
        else:
            self._emit(f"({int_op})")

    def _emit_call(self, instr: LIRCall):
        func_ref = f"$nova_{instr.func_name}"
        self._emit(f"(call {func_ref})")

    def _emit_start_function(self, lir_module: LIRModule):
        """生成 _start 入口函数"""
        self._emit(";; ---- 程序入口 ----")
        self._emit("")

        has_main = "main" in lir_module.functions

        self._emit("(func $_start")
        self.indent_level += 1
        self._emit("(call $nova_init)")
        if has_main:
            self._emit("(call $nova_main)")
        self._emit("(call $nova_cleanup)")
        self.indent_level -= 1
        self._emit(")")

        self._emit("(start $_start)")

        # 关闭 module
        self.indent_level -= 1
        self._emit(")")

    def _get_string_offset(self, string: str) -> int:
        if string not in self.string_table:
            offset = self.string_counter
            encoded = string.encode("utf-8") + b"\\x00"
            self.string_counter += len(encoded)
            self.string_table[string] = offset
        return self.string_table[string]

    def compile_to_wasm(
        self, lir_module: LIRModule, output_path: str, optimize: bool = True
    ) -> bool:
        """编译为 .wasm 文件"""
        wat = self.compile(lir_module)

        # 写入临时 .wat 文件
        with tempfile.NamedTemporaryFile(suffix=".wat", mode="w", delete=False) as f:
            f.write(wat)
            wat_path = f.name

        try:
            # 尝试用 wat2wasm 编译
            cmd = ["wat2wasm", wat_path, "-o", output_path]
            if optimize:
                cmd.append("-O1")

            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            if result.returncode != 0:
                raise RuntimeError(f"Wasm compile failed: {result.stderr}")
        except FileNotFoundError:
            # wat2wasm 不可用，保存 .wat 文件
            wat_output = (
                output_path.rsplit(".", 1)[0] + ".wat"
                if output_path.endswith(".wasm")
                else output_path + ".wat"
            )
            with open(wat_output, "w") as f:
                f.write(wat)
            return False  # 返回 False 表示只生成了 WAT
        finally:
            if os.path.exists(wat_path):
                os.unlink(wat_path)
        return True
