"""
Nova WasmGC 后端
将 LIR 转换为 WebAssembly 文本格式（WAT），支持 GC 提案。
"""

import os
import subprocess
import tempfile
from typing import Dict, List

from ..ir.ir_nodes import (
    INT_TYPE,
    IRType,
    LIRBinOp,
    LIRBranch,
    LIRBuildADT,
    LIRBuildList,
    LIRBuildMap,
    LIRBuildTuple,
    LIRCall,
    LIRCallIndirect,
    LIRClosureCreate,
    LIRFieldAccess,
    LIRFunction,
    LIRIndex,
    LIRInstr,
    LIRJump,
    LIRLabel,
    LIRListAppend,
    LIRLoadConst,
    LIRLoadGlobal,
    LIRLoadReg,
    LIRModule,
    LIRPanic,
    LIRReturn,
    LIRStoreGlobal,
    LIRStoreReg,
    LIRSwitch,
    LIRUnaryOp,
    NovaType,
)

# Wasm 类型映射
WASM_TYPE_MAP = {
    IRType.INT: "i64",
    IRType.FLOAT: "f64",
    IRType.BOOL: "i32",
    IRType.STRING: "i32",
    IRType.UNIT: "",
    IRType.PTR: "i32",
    IRType.CHAR: "i32",
    IRType.LIST: "i32",
    IRType.MAP: "i32",
    IRType.TUPLE: "i32",
    IRType.FUNCTION: "i32",
    IRType.ADT: "i32",
    IRType.NEVER: "",
    IRType.TYPE_VAR: "i32",
}


class WasmGCBackend:
    """将 Nova LIR 编译为 WebAssembly（WasmGC）"""

    def __init__(self):
        """初始化 WasmGC 后端代码生成器

        初始化输出行列表、缩进级别、字符串常量表、字符串计数器，
        以及 LIR 指令调度表。
        """
        self.output_lines: List[str] = []
        self.indent_level = 0
        self.string_table: Dict[str, int] = {}  # 字符串 -> 数据段偏移
        self.string_counter = 0
        self._instr_dispatch = self._build_instr_dispatch_table()

    def compile(self, lir_module: LIRModule) -> str:
        """将 LIR Module 编译为 WAT（WebAssembly Text Format）"""
        self.output_lines = []
        self.string_table = {}
        self.string_counter = 0

        # 预扫描字符串常量
        self._scan_strings(lir_module)

        self._emit_header()
        self._emit_types()
        self._emit_imports()
        self._emit_memory()
        self._emit_globals(lir_module)
        self._emit_string_data()
        self._emit_functions(lir_module)
        self._emit_start_function(lir_module)

        return "\n".join(self.output_lines)

    def _emit(self, line: str = ""):
        indent = "  " * self.indent_level
        self.output_lines.append(indent + line)

    def _emit_header(self):
        self._emit("(;; Generated by Nova WasmGC Backend ;;)")
        self._emit("(;; Supports WasmGC (Garbage Collection) Proposal ;;)")
        self._emit("")
        self._emit("(module $nova")
        self.indent_level += 1

    def _nova_type_to_wasm(self, ty: NovaType) -> str:
        return WASM_TYPE_MAP.get(ty.kind, "i32")

    def _emit_types(self):
        """定义 GC struct 类型（对应 Nova 的 ADT）"""
        self._emit(";; ---- GC 类型定义 ----")
        self._emit("")

        # Option[T] - None
        self._emit("(type $option_none (struct (field $tag i32)))")
        # Option[T] - Some
        self._emit("(type $option_some (struct (field $tag i32) (field $value i64)))")
        self._emit("")

        # Result[T, E] - Ok
        self._emit("(type $result_ok (struct (field $tag i32) (field $value i64)))")
        # Result[T, E] - Err
        self._emit("(type $result_err (struct (field $tag i32) (field $error i64)))")
        self._emit("")

        # 列表 struct（WasmGC struct 类型）
        self._emit("(type $nova_list (struct")
        self.indent_level += 1
        self._emit("(field $length i32)")
        self._emit("(field $capacity i32)")
        self._emit("(field $data i32)")
        self.indent_level -= 1
        self._emit(")")
        self._emit("")

    def _emit_imports(self):
        """导入运行时函数"""
        self._emit(";; ---- 运行时函数导入 ----")
        self._emit("")

        runtime_imports = [
            ('"nova_print"', "(func $nova_print (param i32))"),
            ('"nova_print_int"', "(func $nova_print_int (param i64))"),
            ('"nova_print_float"', "(func $nova_print_float (param f64))"),
            (
                '"nova_string_concat"',
                "(func $nova_string_concat (param i32) (param i32) (result i32))",
            ),
            ('"nova_list_new"', "(func $nova_list_new (param i32) (result i32))"),
            ('"nova_list_push"', "(func $nova_list_push (param i32) (param i64))"),
            (
                '"nova_list_get"',
                "(func $nova_list_get (param i32) (param i32) (result i64))",
            ),
            ('"nova_list_length"', "(func $nova_list_length (param i32) (result i32))"),
            ('"nova_sqrt"', "(func $nova_sqrt (param f64) (result f64))"),
            ('"nova_sin"', "(func $nova_sin (param f64) (result f64))"),
            ('"nova_cos"', "(func $nova_cos (param f64) (result f64))"),
            ('"nova_pow"', "(func $nova_pow (param f64) (param f64) (result f64))"),
            ('"nova_abs"', "(func $nova_abs (param f64) (result f64))"),
            ('"nova_floor"', "(func $nova_floor (param f64) (result f64))"),
            ('"nova_ceil"', "(func $nova_ceil (param f64) (result f64))"),
            ('"nova_round"', "(func $nova_round (param f64) (result f64))"),
            ('"nova_alloc"', "(func $nova_alloc (param i32) (result i32))"),
            ('"nova_free"', "(func $nova_free (param i32))"),
            ('"nova_init"', "(func $nova_init)"),
            ('"nova_cleanup"', "(func $nova_cleanup)"),
            ('"nova_json_parse"', "(func $nova_json_parse (param i32) (result i32))"),
            (
                '"nova_json_stringify"',
                "(func $nova_json_stringify (param i32) (result i32))",
            ),
            ('"nova_panic"', "(func $nova_panic (param i32))"),
        ]

        for name, sig in runtime_imports:
            self._emit(f'(import "nova_runtime" {name} {sig})')
        self._emit("")

    def _emit_memory(self):
        """声明线性内存"""
        self._emit(";; ---- 内存 ----")
        self._emit('(memory (export "memory") 100)')
        self._emit("")

    def _emit_globals(self, lir_module: LIRModule):
        """声明全局变量（对应 LIRModule.globals）

        为每个 LIRGlobal 生成 Wasm global 声明，使后续
        global.get / global.set 指令能正确引用。
        """
        if not lir_module.globals:
            return
        self._emit(";; ---- 全局变量 ----")
        for g in lir_module.globals:
            wasm_type = self._nova_type_to_wasm(g.ir_type)
            # 可变全局变量声明为 (global $name (mut type))
            # 不可变全局变量声明为 (global $name type)（值为 0）
            self._emit(
                f'(global $nova_global_{g.name} (mut {wasm_type}))'
            )
        self._emit("")

    def _scan_strings(self, lir_module: LIRModule):
        """预扫描 LIR 中的字符串常量"""
        offset = 0
        for func in lir_module.functions.values():
            for instr in func.body:
                if isinstance(instr, LIRLoadConst) and instr.const_type == "string":
                    if instr.value not in self.string_table:
                        self.string_table[instr.value] = offset
                        encoded = str(instr.value).encode("utf-8") + b"\x00"
                        offset += len(encoded)

    def _emit_string_data(self):
        """输出字符串数据段"""
        self._emit(";; ---- 数据段 ----")
        if not self.string_table:
            self._emit("")
            return

        # 将所有字符串编码到一个数据段
        for string_val, offset in self.string_table.items():
            escaped = self._escape_wat_string(str(string_val))
            self._emit(f'(data (i32.const {offset}) "{escaped}\\00")')
        self._emit("")

    def _escape_wat_string(self, s: str) -> str:
        """转义字符串为 WAT 格式"""
        result = []
        for ch in s:
            if ch == '"':
                result.append('\\"')
            elif ch == "\\":
                result.append("\\\\")
            elif ch == "\n":
                result.append("\\n")
            elif ch == "\t":
                result.append("\\t")
            elif ch == "\r":
                result.append("\\r")
            elif 0x20 <= ord(ch) < 0x7F:
                result.append(ch)
            else:
                result.append(f"\\{ord(ch):02x}")
        return "".join(result)

    def _emit_functions(self, lir_module: LIRModule):
        """编译所有函数"""
        self._emit(";; ---- 函数定义 ----")
        self._emit("")

        for name, func in lir_module.functions.items():
            self._compile_function(name, func)

    def _compile_function(self, name: str, func: LIRFunction):
        """编译函数体，采用 PC + br_table 方案支持任意 CFG

        Wasm 的结构化控制流（block/loop/if）无法直接表达任意 goto CFG。
        采用显式 PC 变量 + br_table 方案，将任意 CFG 转换为一个大循环
        内的分派表，支持前向跳转、后向跳转、循环等所有控制流模式。

        结构：
          (func $name (param ...) (result ...)
            (local $pc i32)    ;; 程序计数器（基本块索引）
            (local ...)         ;; 其他虚拟寄存器
            (block $exit       ;; 出口块（return 跳出用）
              (loop $dispatch  ;; 分派循环
                ;; 根据 $pc 跳转到对应基本块
                (local.get $pc)
                (br_table $bb0 $bb1 ... $bbN $exit)
                (block $bb0    ;; 基本块 0
                  ... 指令 ...
                  (local.set $pc <next_pc>)
                  (br $dispatch)  ;; 回到循环顶部重新分派
                )
                (block $bb1
                  ...
                )
                ...
              ) ;; end loop
            ) ;; end exit block
          ) ;; end func
        """
        params_parts = []
        for loc, ty in func.params:
            wasm_ty = self._nova_type_to_wasm(ty)
            if wasm_ty:
                params_parts.append(f"(param ${loc} {wasm_ty})")
        params_str = " ".join(params_parts)

        ret_ty = self._nova_type_to_wasm(func.return_type)
        result_str = f"(result {ret_ty})" if ret_ty else ""

        self._emit(f"(func $nova_{name} {params_str} {result_str}")
        self.indent_level += 1

        # 第一步：收集所有标签（基本块）并分配 PC 索引
        label_to_pc: Dict[str, int] = {}
        pc_counter = 0

        # 第一个基本块（函数入口，可能没有显式 Label）
        # 检查 body 第一条是不是 Label，如果不是，函数开头本身是一个隐式块
        has_entry_label = False
        if func.body and isinstance(func.body[0], LIRLabel):
            has_entry_label = True

        for instr in func.body:
            if isinstance(instr, LIRLabel):
                if instr.name not in label_to_pc:
                    label_to_pc[instr.name] = pc_counter
                    pc_counter += 1

        # 声明 PC 局部变量，初始值为 0（第一个基本块）
        self._emit("(local $pc i32)")
        # 初始 PC = 0（第一个基本块）
        self._emit("(i32.const 0)")
        self._emit("(local.set $pc)")

        self._emit("")
        self._emit(";; ---- 控制流：PC + br_table 方案 ----")
        self._emit("")

        # 出口块（return 时跳出到这里）
        self._emit("(block $exit")
        self.indent_level += 1

        # 分派循环
        self._emit("(loop $dispatch")
        self.indent_level += 1

        # br_table：根据 $pc 跳转到对应基本块
        # 格式: (br_table $bb0 $bb1 ... $default)
        br_targets = []
        for i in range(pc_counter):
            br_targets.append(f"$bb{i}")
        # 默认目标：退出循环（异常情况）
        br_targets.append("$exit")
        self._emit(f"(local.get $pc)")
        self._emit(f"(br_table {' '.join(br_targets)})")
        self._emit("")

        # 第二步：编译每个基本块
        # 将线性指令序列按 Label 切分为基本块
        current_block_idx = 0
        current_block_label = None
        in_first_block = not has_entry_label

        for instr in func.body:
            if isinstance(instr, LIRLabel):
                # 新基本块开始
                # 如果之前在一个块里，需要关闭它（但第一个隐式块特殊处理）
                if current_block_label is not None or in_first_block:
                    # 上一个块应该已经在 Jump/Branch/Return 处处理了结束
                    pass

                block_idx = label_to_pc[instr.name]
                current_block_label = instr.name
                current_block_idx = block_idx
                in_first_block = False

                # 开一个 block 对应这个基本块
                self._emit(f"(block $bb{block_idx}")
                self.indent_level += 1
                self._emit(f";; --- 基本块 {block_idx}: {instr.name} ---")

            elif isinstance(instr, LIRJump):
                # 无条件跳转：设置新 PC，br 回 dispatch 循环
                target_pc = label_to_pc.get(instr.target, 0)
                self._emit(f"(i32.const {target_pc})")
                self._emit("(local.set $pc)")
                self._emit("(br $dispatch)")
                # 关闭当前 block
                self.indent_level -= 1
                self._emit(")")
                self._emit("")

            elif isinstance(instr, LIRBranch):
                # 条件分支：根据条件设置不同的 PC，然后 br 回 dispatch
                # 注意：Wasm br_if 是条件为真时跳转，我们需要：
                # 条件为真 → 跳 true_target，条件为假 → 跳 false_target
                true_pc = label_to_pc.get(instr.true_target, 0)
                false_pc = label_to_pc.get(instr.false_target, 0)

                if instr.src_locs:
                    self._emit(f"(local.get ${instr.src_locs[0][0]})")
                # 条件为真时跳到 true 块，否则继续到 false 块
                # 使用 if-else 结构设置 PC
                self._emit("(if")
                self.indent_level += 1
                self._emit("(then")
                self.indent_level += 1
                self._emit(f"(i32.const {true_pc})")
                self._emit("(local.set $pc)")
                self.indent_level -= 1
                self._emit(")")
                self._emit("(else")
                self.indent_level += 1
                self._emit(f"(i32.const {false_pc})")
                self._emit("(local.set $pc)")
                self.indent_level -= 1
                self._emit(")")
                self.indent_level -= 1
                self._emit(")")
                self._emit("(br $dispatch)")
                # 关闭当前 block
                self.indent_level -= 1
                self._emit(")")
                self._emit("")

            elif isinstance(instr, LIRSwitch):
                # switch 多分支：使用 if-else 级联比较，设置 PC 后 br $dispatch
                default_pc = label_to_pc.get(instr.default_target, 0)

                if instr.src_locs and instr.cases:
                    val_loc = instr.src_locs[0][0]
                    val_type = instr.src_locs[0][1] if len(instr.src_locs[0]) > 1 else INT_TYPE
                    wasm_type = WASM_TYPE_MAP.get(val_type, "i64")

                    # 生成嵌套 if-else：每个 case 一个比较
                    # 从后往前生成，实现 else if 嵌套
                    for case_val, target in reversed(instr.cases):
                        target_pc = label_to_pc.get(target, 0)
                        # 将值压栈
                        self._emit(f"(local.get ${val_loc})")
                        # 将 case 值压栈
                        if isinstance(case_val, int):
                            self._emit(f"({wasm_type}.const {case_val})")
                        elif isinstance(case_val, float):
                            self._emit(f"({wasm_type}.const {case_val})")
                        else:
                            # 字符串等复杂类型暂时用 default 处理
                            self._emit(f"({wasm_type}.const 0)")
                        # 比较
                        self._emit(f"({wasm_type}.eq)")
                        # if 结构
                        self._emit("(if")
                        self.indent_level += 1
                        self._emit("(then")
                        self.indent_level += 1
                        self._emit(f"(i32.const {target_pc})")
                        self._emit("(local.set $pc)")
                        self.indent_level -= 1
                        self._emit(")")
                        self._emit("(else")
                        self.indent_level += 1

                    # default 分支（最内层 else）
                    self._emit(f"(i32.const {default_pc})")
                    self._emit("(local.set $pc)")

                    # 闭合所有 if-else
                    for _ in instr.cases:
                        self.indent_level -= 1
                        self._emit(")")
                        self.indent_level -= 1
                        self._emit(")")
                else:
                    # 没有值或没有 case，直接跳 default
                    self._emit(f"(i32.const {default_pc})")
                    self._emit("(local.set $pc)")

                self._emit("(br $dispatch)")
                # 关闭当前 block
                self.indent_level -= 1
                self._emit(")")
                self._emit("")

            elif isinstance(instr, LIRReturn):
                # 返回：跳出 exit 块（即函数返回）
                self._emit("(br $exit)")
                # 关闭当前 block
                self.indent_level -= 1
                self._emit(")")
                self._emit("")

            elif isinstance(instr, LIRPanic):
                # Panic：调用 panic 函数，然后 unreachable
                self._compile_instr(instr, func)
                # 关闭当前 block（panic 后不会继续执行）
                self.indent_level -= 1
                self._emit(")")
                self._emit("")

            else:
                # 普通指令
                self._compile_instr(instr, func)

        # 如果最后一个基本块没有以 Jump/Branch/Return/Panic 结尾
        # （理论上不应该发生，但防御性处理）
        # 检查是否有未关闭的 block（通过看 indent_level 判断）
        # 这里简单地关闭所有打开的基本块 block
        # 实际上，正常的 LIR 每个块都应该有终结指令

        # 关闭 dispatch loop
        self.indent_level -= 1
        self._emit(") ;; end loop $dispatch")

        # 关闭 exit block
        self.indent_level -= 1
        self._emit(") ;; end block $exit")

        self.indent_level -= 1
        self._emit(")")
        self._emit("")

    def _build_instr_dispatch_table(self) -> dict:
        """构建 LIR 指令类型 → 编译方法 的调度表

        使用类型 → 方法 的调度表模式替代长 if-isinstance 链，
        圈复杂度从 ~19 降至 ~3，提升可维护性和可扩展性。
        """
        return {
            # 常量与加载/存储
            LIRLoadConst: self._compile_load_const,
            LIRLoadReg: self._compile_load_reg,
            LIRStoreReg: self._compile_store_reg,
            LIRLoadGlobal: self._compile_load_global,
            LIRStoreGlobal: self._compile_store_global,
            # 运算
            LIRBinOp: self._compile_binop,
            LIRUnaryOp: self._compile_unary_op,
            # 函数调用
            LIRCall: self._compile_call,
            LIRCallIndirect: self._compile_call_indirect,
            # 返回
            LIRReturn: self._compile_return,
            # 数据结构构建
            LIRBuildList: self._compile_build_list,
            LIRBuildMap: self._compile_build_map,
            LIRBuildTuple: self._compile_build_tuple,
            LIRBuildADT: self._compile_build_adt,
            # 闭包
            LIRClosureCreate: self._compile_closure_create,
            # 访问
            LIRFieldAccess: self._compile_field_access,
            LIRIndex: self._compile_index_access,
            # 列表操作
            LIRListAppend: self._compile_list_append,
            # 杂项
            LIRPanic: self._compile_panic,
        }

    def _compile_instr(self, instr: LIRInstr, func: LIRFunction):
        """编译非控制流指令（调度表分发）

        使用类型 → 方法 的调度表模式替代长 if-isinstance 链，
        圈复杂度从 ~19 降至 ~3。
        """
        handler = self._instr_dispatch.get(type(instr))
        if handler:
            handler(instr)
        else:
            self._emit(
                f"(;; TODO: LIR instruction {type(instr).__name__} not implemented ;;)"
            )

    # ---- 各指令类型的独立编译方法 ----

    def _compile_load_const(self, instr: LIRLoadConst):
        """编译常量加载"""
        self._emit_load_const(instr)

    def _compile_load_reg(self, instr: LIRLoadReg):
        """编译寄存器加载"""
        if instr.src_locs:
            self._emit(f"(local.get ${instr.src_locs[0][0]})")

    def _compile_store_reg(self, instr: LIRStoreReg):
        """编译寄存器存储"""
        if instr.dst_loc:
            self._emit(f"(local.set ${instr.dst_loc[0]})")

    def _compile_load_global(self, instr: LIRLoadGlobal):
        """编译全局变量加载"""
        self._emit(f"(global.get $nova_global_{instr.global_name})")

    def _compile_store_global(self, instr: LIRStoreGlobal):
        """编译全局变量存储"""
        self._emit(f"(global.set $nova_global_{instr.global_name})")

    def _compile_binop(self, instr: LIRBinOp):
        """编译二元运算"""
        self._emit_binop(instr)

    def _compile_unary_op(self, instr: LIRUnaryOp):
        """编译一元运算"""
        if instr.op == "-":
            if instr.src_locs:
                src_ty = instr.src_locs[0][1] if instr.src_locs else INT_TYPE
                if src_ty.kind == IRType.FLOAT:
                    self._emit("(f64.neg)")
                else:
                    self._emit("(i64.neg)")
        elif instr.op == "!":
            self._emit("(i32.eqz)")

    def _compile_call(self, instr: LIRCall):
        """编译函数调用"""
        self._emit_call(instr)

    def _compile_call_indirect(self, instr: LIRCallIndirect):
        """编译间接调用（闭包调用）

        调用 nova_closure_call(closure, args_array, arg_count)。
        简化实现：零参数闭包直接调用，多参数暂不支持。
        """
        if instr.arg_count > 0:
            # 对于多参数闭包调用，需要打包参数数组
            # 简化处理：暂不支持多参数间接调用，使用占位
            pass
        # 零参数闭包：直接调用
        self._emit("(i32.const 0)")  # 空参数数组指针
        self._emit("(i32.const 0)")  # 参数数量 0
        self._emit("(call $nova_closure_call)")

    def _compile_return(self, instr: LIRReturn):
        """编译返回指令"""
        self._emit("(return)")

    def _compile_build_list(self, instr: LIRBuildList):
        """编译列表构建"""
        self._emit(f"(i32.const {instr.count})")
        self._emit("(call $nova_list_new)")

    def _compile_build_map(self, instr: LIRBuildMap):
        """编译映射构建"""
        self._emit(f"(i32.const {instr.entry_count})")
        self._emit("(call $nova_map_new)")

    def _compile_build_tuple(self, instr: LIRBuildTuple):
        """编译元组构建"""
        self._emit(f"(i32.const {instr.count * 8})")
        self._emit("(call $nova_alloc)")

    def _compile_build_adt(self, instr: LIRBuildADT):
        """编译 ADT 构建"""
        self._emit(f"(i32.const {instr.type_tag})")
        self._emit(f"(i32.const {instr.field_count * 8 + 8})")
        self._emit("(call $nova_alloc)")

    def _compile_closure_create(self, instr: LIRClosureCreate):
        """编译闭包创建

        当前阶段：占位实现，返回空指针（i32.const 0）。
        lambda 函数体的 Wasm 编译待后续实现。
        """
        # 占位：返回空闭包指针
        self._emit("(i32.const 0)")

    def _compile_field_access(self, instr: LIRFieldAccess):
        """编译字段访问

        字段索引乘以 8（每个字段 8 字节，NovaValue 大小）。
        """
        offset = instr.offset * 8
        self._emit(f"(i32.const {offset})")
        self._emit("(i32.add)")
        self._emit("(i64.load align=8)")

    def _compile_index_access(self, instr: LIRIndex):
        """编译索引访问

        索引访问：base + index * 8（每个元素 8 字节）。
        栈上已有 [base_ptr, index]，需要计算 base + index * 8。
        """
        self._emit("(i64.const 8)")
        self._emit("(i64.mul)")
        self._emit("(i32.wrap_i64)")
        self._emit("(i32.add)")
        self._emit("(i64.load align=8)")

    def _compile_list_append(self, instr: LIRListAppend):
        """编译列表追加元素

        调用 nova_list_push(list_ptr, elem_value)。
        栈上已有 [list_ptr, elem_value]，顺序正确。
        """
        self._emit("(call $nova_list_push)")

    def _compile_panic(self, instr: LIRPanic):
        """编译 Panic 指令"""
        self._emit("(i32.const 0)")
        self._emit("(call $nova_panic)")
        self._emit("(unreachable)")

    def _emit_load_const(self, instr: LIRLoadConst):
        if instr.const_type == "int":
            self._emit(f"(i64.const {instr.value})")
        elif instr.const_type == "float":
            self._emit(f"(f64.const {repr(instr.value)})")
        elif instr.const_type == "bool":
            self._emit(f"(i32.const {1 if instr.value else 0})")
        elif instr.const_type == "string":
            offset = self._get_string_offset(str(instr.value))
            self._emit(f"(i32.const {offset})")
        # unit: 无值

    def _emit_binop(self, instr: LIRBinOp):
        op_map = {
            "+": ("i64.add", "f64.add"),
            "-": ("i64.sub", "f64.sub"),
            "*": ("i64.mul", "f64.mul"),
            "/": ("i64.div_s", "f64.div"),
            "%": ("i64.rem_s", "call $nova_fmod"),
            "==": ("i64.eq", "f64.eq"),
            "!=": ("i64.ne", "f64.ne"),
            "<": ("i64.lt_s", "f64.lt"),
            ">": ("i64.gt_s", "f64.gt"),
            "<=": ("i64.le_s", "f64.le"),
            ">=": ("i64.ge_s", "f64.ge"),
        }

        int_op, float_op = op_map.get(instr.op, ("i64.add", "f64.add"))

        # 检查是否是浮点操作
        is_float = False
        if instr.src_locs:
            src_ty = instr.src_locs[0][1] if instr.src_locs else INT_TYPE
            if src_ty.kind == IRType.FLOAT:
                is_float = True

        if is_float and float_op:
            self._emit(f"({float_op})")
        else:
            self._emit(f"({int_op})")

    def _emit_call(self, instr: LIRCall):
        # LIRCall 的属性是 callee，不是 func_name
        func_ref = f"$nova_{instr.callee}"
        self._emit(f"(call {func_ref})")

    def _emit_start_function(self, lir_module: LIRModule):
        """生成 _start 入口函数"""
        self._emit(";; ---- 程序入口 ----")
        self._emit("")

        has_main = "main" in lir_module.functions

        self._emit("(func $_start")
        self.indent_level += 1
        self._emit("(call $nova_init)")
        if has_main:
            self._emit("(call $nova_main)")
        self._emit("(call $nova_cleanup)")
        self.indent_level -= 1
        self._emit(")")

        self._emit("(start $_start)")

        # 关闭 module
        self.indent_level -= 1
        self._emit(")")

    def _get_string_offset(self, string: str) -> int:
        if string not in self.string_table:
            offset = self.string_counter
            encoded = string.encode("utf-8") + b"\x00"
            self.string_counter += len(encoded)
            self.string_table[string] = offset
        return self.string_table[string]

    def compile_to_wasm(
        self, lir_module: LIRModule, output_path: str, optimize: bool = True
    ) -> bool:
        """编译为 .wasm 文件"""
        wat = self.compile(lir_module)

        # 写入临时 .wat 文件
        with tempfile.NamedTemporaryFile(suffix=".wat", mode="w", delete=False) as f:
            f.write(wat)
            wat_path = f.name

        try:
            # 尝试用 wat2wasm 编译
            cmd = ["wat2wasm", wat_path, "-o", output_path]
            if optimize:
                cmd.append("-O1")

            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            if result.returncode != 0:
                raise RuntimeError(f"Wasm compile failed: {result.stderr}")
        except FileNotFoundError:
            # wat2wasm 不可用，保存 .wat 文件
            wat_output = (
                output_path.rsplit(".", 1)[0] + ".wat"
                if output_path.endswith(".wasm")
                else output_path + ".wat"
            )
            with open(wat_output, "w") as f:
                f.write(wat)
            return False  # 返回 False 表示只生成了 WAT
        finally:
            if os.path.exists(wat_path):
                os.unlink(wat_path)
        return True
