"""
Nova 后端测试 - Cranelift、WasmGC、编译管道
"""

import unittest
import os
import tempfile

from nova.ir.ir_nodes import (
    IRType,
    NovaType,
    INT_TYPE,
    FLOAT_TYPE,
    STRING_TYPE,
    BOOL_TYPE,
    UNIT_TYPE,
    LIRModule,
    LIRFunction,
    LIRLoadConst,
    LIRBinOp,
    LIRCall,
    LIRReturn,
    LIRLabel,
    HIRModule,
    MIRModule,
    LIRInstr,
)
from nova.backend.cranelift_backend import CraneliftBackend
from nova.backend.wasm_backend import WasmGCBackend
from nova.backend.compiler_pipeline import NovaCompilerPipeline, BACKEND_NATIVE, BACKEND_WASM, BACKEND_C


# ============================================================
# 辅助函数：从 Nova 源码生成 LIR
# ============================================================

def source_to_lir(source: str) -> LIRModule:
    """完整的 Nova 源码 -> LIR 管道"""
    from nova.lexer import Lexer
    from nova.parser import Parser
    from nova.type_checker import TypeChecker
    from nova.ir.hir_lowering import HIRLowering
    from nova.ir.mir_lowering import MIRLowering
    from nova.ir.lir_lowering import LIRLowering

    tokens = Lexer(source).tokenize()
    ast = Parser(tokens).parse()
    TypeChecker().check_program(ast)

    hir = HIRLowering().lower(ast)
    mir = MIRLowering().lower(hir)
    lir = LIRLowering().lower(mir)
    return lir


def make_simple_lir_module() -> LIRModule:
    """创建简单的 LIR Module 用于测试"""
    module = LIRModule(name="test")

    func = LIRFunction(
        name="add",
        params=[("r0", INT_TYPE), ("r1", INT_TYPE)],
        return_type=INT_TYPE,
    )
    func.body = [
        LIRLabel(name="bb0"),
        LIRLoadConst(value=0, const_type="int"),
        LIRLoadConst(value=0, const_type="int"),
        LIRBinOp(op="+"),
        LIRReturn(),
    ]
    # 设置 src_locs / dst_loc
    func.body[1].dst_loc = ("r2", INT_TYPE)
    func.body[2].dst_loc = ("r3", INT_TYPE)
    func.body[3].src_locs = [("r2", INT_TYPE), ("r3", INT_TYPE)]
    func.body[3].dst_loc = ("r4", INT_TYPE)

    module.functions["add"] = func
    return module


def make_main_lir_module() -> LIRModule:
    """创建包含 main 的 LIR Module"""
    module = LIRModule(name="test_main")

    func = LIRFunction(
        name="main",
        params=[],
        return_type=UNIT_TYPE,
    )
    func.body = [
        LIRLabel(name="bb0"),
        LIRLoadConst(value="Hello", const_type="string"),
        LIRCall(func_name="nova_print", arg_count=1),
        LIRReturn(),
    ]
    func.body[1].dst_loc = ("r0", STRING_TYPE)
    func.body[2].src_locs = [("r0", STRING_TYPE)]
    func.body[2].dst_loc = ("r1", UNIT_TYPE)

    module.functions["main"] = func
    return module


# ============================================================
# Cranelift 后端测试
# ============================================================

class TestCraneliftBackend(unittest.TestCase):

    def test_compile_basic(self):
        """测试基本的 Cranelift IR 生成"""
        backend = CraneliftBackend()
        module = make_simple_lir_module()
        clif = backend.compile(module)
        self.assertIn("function", clif)
        self.assertIn("nova_add", clif)

    def test_target_detection(self):
        """测试目标平台检测"""
        backend = CraneliftBackend()
        target = backend._detect_target()
        self.assertIn(target, ["x86_64", "aarch64", "riscv64"])

    def test_compile_with_data_section(self):
        """测试数据段生成"""
        backend = CraneliftBackend()
        module = make_main_lir_module()
        clif = backend.compile(module)
        self.assertIn("nova_main", clif)

    def test_header_contains_target(self):
        """测试头部包含目标信息"""
        backend = CraneliftBackend()
        module = make_simple_lir_module()
        clif = backend.compile(module)
        self.assertIn("target", clif)
        self.assertIn("Generated by Nova Cranelift Backend", clif)

    def test_fallback_no_cranelift(self):
        """测试 Cranelift 不可用时的 fallback"""
        backend = CraneliftBackend()
        module = make_simple_lir_module()

        with tempfile.TemporaryDirectory() as tmpdir:
            output = os.path.join(tmpdir, "test.o")
            result = backend.compile_to_object(module, output)
            # 应该 fallback 到 .clif 文件
            self.assertTrue(result.endswith(".clif"))

    def test_type_map(self):
        """测试 Cranelift 类型映射完整性"""
        from nova.backend.cranelift_backend import CRANELIFT_TYPE_MAP
        self.assertIn(IRType.INT, CRANELIFT_TYPE_MAP)
        self.assertIn(IRType.FLOAT, CRANELIFT_TYPE_MAP)
        self.assertIn(IRType.BOOL, CRANELIFT_TYPE_MAP)
        self.assertIn(IRType.STRING, CRANELIFT_TYPE_MAP)
        self.assertIn(IRType.UNIT, CRANELIFT_TYPE_MAP)


# ============================================================
# WasmGC 后端测试
# ============================================================

class TestWasmGCBackend(unittest.TestCase):

    def test_basic_wat(self):
        """测试基本的 WAT 生成"""
        backend = WasmGCBackend()
        module = make_main_lir_module()
        wat = backend.compile(module)
        self.assertIn("(module", wat)
        self.assertIn("(func", wat)
        self.assertIn("nova_main", wat)

    def test_gc_struct_types(self):
        """测试 GC struct 类型定义"""
        backend = WasmGCBackend()
        module = make_main_lir_module()
        wat = backend.compile(module)
        self.assertIn("struct", wat)
        self.assertTrue(
            "option_none" in wat or "nova_list" in wat
        )

    def test_imports(self):
        """测试运行时函数导入"""
        backend = WasmGCBackend()
        module = make_main_lir_module()
        wat = backend.compile(module)
        self.assertIn("(import", wat)
        self.assertIn("nova_runtime", wat)
        self.assertIn("nova_print", wat)

    def test_start_function(self):
        """测试 _start 入口函数"""
        backend = WasmGCBackend()
        module = make_main_lir_module()
        wat = backend.compile(module)
        self.assertIn("$_start", wat)
        self.assertIn("(start $_start)", wat)

    def test_memory_declaration(self):
        """测试内存声明"""
        backend = WasmGCBackend()
        module = make_main_lir_module()
        wat = backend.compile(module)
        self.assertIn("(memory", wat)

    def test_nova_init_called(self):
        """测试 nova_init 在 _start 中被调用"""
        backend = WasmGCBackend()
        module = make_main_lir_module()
        wat = backend.compile(module)
        self.assertIn("$nova_init", wat)

    def test_wasm_type_map(self):
        """测试 Wasm 类型映射"""
        from nova.backend.wasm_backend import WASM_TYPE_MAP
        self.assertEqual(WASM_TYPE_MAP[IRType.INT], "i64")
        self.assertEqual(WASM_TYPE_MAP[IRType.FLOAT], "f64")
        self.assertEqual(WASM_TYPE_MAP[IRType.BOOL], "i32")
        self.assertEqual(WASM_TYPE_MAP[IRType.UNIT], "")

    def test_string_data_segment(self):
        """测试字符串数据段"""
        backend = WasmGCBackend()
        module = make_main_lir_module()
        wat = backend.compile(module)
        self.assertIn("data", wat)

    def test_list_struct_type(self):
        """测试列表 GC struct 定义"""
        backend = WasmGCBackend()
        module = LIRModule(name="test")
        wat = backend.compile(module)
        self.assertIn("$nova_list", wat)
        self.assertIn("$length", wat)


# ============================================================
# 编译管道测试
# ============================================================

class TestCompilerPipeline(unittest.TestCase):

    def test_pipeline_creation_native(self):
        """测试原生目标管道创建"""
        pipeline = NovaCompilerPipeline(target=BACKEND_NATIVE, optimize_level=0)
        self.assertIsNotNone(pipeline.backend)
        self.assertEqual(pipeline.target, BACKEND_NATIVE)

    def test_pipeline_creation_wasm(self):
        """测试 WasmGC 目标管道创建"""
        pipeline = NovaCompilerPipeline(target=BACKEND_WASM, optimize_level=0)
        self.assertIsNotNone(pipeline.backend)
        self.assertEqual(pipeline.target, BACKEND_WASM)

    def test_pipeline_creation_c(self):
        """测试 C 目标管道创建"""
        pipeline = NovaCompilerPipeline(target=BACKEND_C, optimize_level=0)
        self.assertIsNotNone(pipeline.backend)
        self.assertEqual(pipeline.target, BACKEND_C)

    def test_pipeline_c_codegen(self):
        """测试 C 后端管道完整编译"""
        pipeline = NovaCompilerPipeline(target=BACKEND_C, optimize_level=0)
        source = 'fn main() -> Unit { print("Hello Pipeline!") }'
        with tempfile.TemporaryDirectory() as tmpdir:
            output = os.path.join(tmpdir, "test_pipeline.c")
            result = pipeline.compile_source(source, output)
            self.assertTrue(result)
            self.assertTrue(os.path.exists(output))
            with open(output) as f:
                c_code = f.read()
            self.assertIn("#include", c_code)

    def test_pipeline_no_optimize(self):
        """测试无优化级别"""
        pipeline = NovaCompilerPipeline(target=BACKEND_C, optimize_level=0)
        self.assertIsNone(pipeline.pass_manager)

    def test_pipeline_with_optimize(self):
        """测试有优化级别"""
        pipeline = NovaCompilerPipeline(target=BACKEND_C, optimize_level=2)
        self.assertIsNotNone(pipeline.pass_manager)

    def test_compile_to_ir_text_hir(self):
        """测试输出 HIR 文本"""
        pipeline = NovaCompilerPipeline(target=BACKEND_C, optimize_level=0)
        source = "fn add(a: Int, b: Int) -> Int { a + b }"
        ir_text = pipeline.compile_to_ir_text(source, "hir")
        self.assertIn("HIRModule", ir_text)

    def test_compile_to_ir_text_mir(self):
        """测试输出 MIR 文本"""
        pipeline = NovaCompilerPipeline(target=BACKEND_C, optimize_level=0)
        source = "fn add(a: Int, b: Int) -> Int { a + b }"
        ir_text = pipeline.compile_to_ir_text(source, "mir")
        self.assertIn("MIRModule", ir_text)

    def test_compile_to_ir_text_lir(self):
        """测试输出 LIR 文本"""
        pipeline = NovaCompilerPipeline(target=BACKEND_C, optimize_level=0)
        source = "fn add(a: Int, b: Int) -> Int { a + b }"
        ir_text = pipeline.compile_to_ir_text(source, "lir")
        self.assertIn("LIRModule", ir_text)


# ============================================================
# 端到端集成测试
# ============================================================

class TestBackendIntegration(unittest.TestCase):

    def test_cranelift_from_source(self):
        """从 Nova 源码到 Cranelift IR"""
        source = "fn add(a: Int, b: Int) -> Int { a + b }"
        lir = source_to_lir(source)

        backend = CraneliftBackend()
        clif = backend.compile(lir)
        self.assertIn("nova_add", clif)
        self.assertIn("function", clif)

    def test_wasm_from_source(self):
        """从 Nova 源码到 WasmGC"""
        source = 'fn main() -> Unit { print("Hello Wasm!") }'
        lir = source_to_lir(source)

        backend = WasmGCBackend()
        wat = backend.compile(lir)
        self.assertIn("(module", wat)
        self.assertIn("nova_main", wat)

    def test_wasm_with_math(self):
        """从含数学运算的源码到 WasmGC"""
        source = "fn square(x: Float) -> Float { x * x }"
        lir = source_to_lir(source)

        backend = WasmGCBackend()
        wat = backend.compile(lir)
        self.assertIn("nova_square", wat)

    def test_wasm_with_print_int(self):
        """含 print_int 的 Wasm 编译"""
        source = 'fn main() -> Unit { print("test") }'
        lir = source_to_lir(source)

        backend = WasmGCBackend()
        wat = backend.compile(lir)
        self.assertIn("nova_print", wat)

    def test_full_pipeline_wasm_output(self):
        """完整管道输出 WAT 文件"""
        pipeline = NovaCompilerPipeline(target=BACKEND_WASM, optimize_level=0)
        source = 'fn main() -> Unit { print("Hello") }'
        with tempfile.TemporaryDirectory() as tmpdir:
            output = os.path.join(tmpdir, "test.wasm")
            result = pipeline.compile_source(source, output)
            # wat2wasm 不可用，会生成 .wat
            self.assertFalse(result)  # False 表示只生成了 WAT


class TestWasmBackendClosure(unittest.TestCase):
    """Wasm 后端闭包 fn_ptr 回填测试"""

    def _make_closure_lir_module(self):
        """创建包含闭包创建和调用的 LIR Module 用于测试"""
        from nova.ir.ir_nodes import (
            LIRClosureCreate, LIRCallIndirect, CLOSURE_TYPE,
        )

        module = LIRModule(name="test_wasm_closure")

        # main 函数：创建闭包并调用
        main_fn = LIRFunction(
            name="main",
            params=[],
            return_type=INT_TYPE,
        )
        main_fn.body = [
            LIRLabel(name="bb0"),
            LIRLoadConst(value=5, const_type="int"),       # r0 = 5 (捕获变量)
            LIRLoadConst(value=10, const_type="int"),      # r1 = 10 (用户参数)
            LIRClosureCreate(fn_name="__lambda_0", capture_count=1),  # r2 = closure
            LIRCallIndirect(arg_count=1),                  # r3 = closure(r1)
            LIRReturn(),
        ]
        main_fn.body[1].dst_loc = ("r0", INT_TYPE)
        main_fn.body[2].dst_loc = ("r1", INT_TYPE)
        main_fn.body[3].src_locs = [("r0", INT_TYPE)]
        main_fn.body[3].dst_loc = ("r2", CLOSURE_TYPE)
        main_fn.body[4].src_locs = [("r2", CLOSURE_TYPE), ("r1", INT_TYPE)]
        main_fn.body[4].dst_loc = ("r3", INT_TYPE)

        # lambda 函数
        lambda_fn = LIRFunction(
            name="__lambda_0",
            params=[("captured_n", INT_TYPE), ("x", INT_TYPE)],
            return_type=INT_TYPE,
        )
        lambda_fn.body = [
            LIRLabel(name="bb0"),
            LIRLoadConst(value=0, const_type="int"),
            LIRReturn(),
        ]
        lambda_fn.body[1].dst_loc = ("r0", INT_TYPE)

        module.functions["main"] = main_fn
        module.functions["__lambda_0"] = lambda_fn
        return module

    def test_wasm_closure_fn_ptr_not_null(self):
        """闭包创建时 fn_ptr 不再是 NULL，而是 table 索引"""
        module = self._make_closure_lir_module()
        backend = WasmGCBackend()
        wat = backend.compile(module)
        # 应包含 nova_closure_new 调用
        self.assertIn("nova_closure_new", wat)
        # __lambda_0 应被分配 table 索引 0
        self.assertEqual(backend.lambda_table_indices.get("__lambda_0"), 0)
        # WAT 中应包含 i32.const 0 作为 fn_ptr（table 索引）
        # 注意：fn_ptr 是 nova_closure_new 的第一个参数，在 call 之前压栈
        self.assertIn("(call $nova_closure_new)", wat)

    def test_wasm_funcref_table_declared(self):
        """WAT 应声明 funcref table"""
        module = self._make_closure_lir_module()
        backend = WasmGCBackend()
        wat = backend.compile(module)
        self.assertIn("table", wat)
        self.assertIn("funcref", wat)

    def test_wasm_elem_segment(self):
        """WAT 应包含 elem 段，将 lambda 函数填入 table"""
        module = self._make_closure_lir_module()
        backend = WasmGCBackend()
        wat = backend.compile(module)
        self.assertIn("elem", wat)
        self.assertIn("$nova___lambda_0", wat)

    def test_wasm_lambda_table_index(self):
        """lambda 函数应被分配 table 索引 0"""
        module = self._make_closure_lir_module()
        backend = WasmGCBackend()
        backend.compile(module)
        self.assertIn("__lambda_0", backend.lambda_table_indices)
        self.assertEqual(backend.lambda_table_indices["__lambda_0"], 0)

    def test_wasm_no_lambda_no_table_growth(self):
        """无 lambda 函数时 table 大小为 1（最小值）"""
        from nova.ir.ir_nodes import LIRPanic
        module = LIRModule(name="test_no_closure")
        main_fn = LIRFunction(name="main", params=[], return_type=UNIT_TYPE)
        main_fn.body = [LIRLabel(name="bb0"), LIRReturn()]
        module.functions["main"] = main_fn
        backend = WasmGCBackend()
        wat = backend.compile(module)
        self.assertIn("(table 1 funcref)", wat)

    def test_wasm_multiple_lambdas_indexed(self):
        """多个 lambda 函数应被分配连续索引"""
        from nova.ir.ir_nodes import LIRClosureCreate, CLOSURE_TYPE
        module = LIRModule(name="test_multi_lambda")
        main_fn = LIRFunction(name="main", params=[], return_type=INT_TYPE)
        main_fn.body = [
            LIRLabel(name="bb0"),
            LIRLoadConst(value=1, const_type="int"),
            LIRClosureCreate(fn_name="__lambda_0", capture_count=0),
            LIRLoadConst(value=2, const_type="int"),
            LIRClosureCreate(fn_name="__lambda_1", capture_count=0),
            LIRReturn(),
        ]
        main_fn.body[1].dst_loc = ("r0", INT_TYPE)
        main_fn.body[2].src_locs = []
        main_fn.body[2].dst_loc = ("r1", CLOSURE_TYPE)
        main_fn.body[3].dst_loc = ("r2", INT_TYPE)
        main_fn.body[4].src_locs = []
        main_fn.body[4].dst_loc = ("r3", CLOSURE_TYPE)

        for lname in ["__lambda_0", "__lambda_1"]:
            lfn = LIRFunction(name=lname, params=[("x", INT_TYPE)], return_type=INT_TYPE)
            lfn.body = [LIRLabel(name="bb0"), LIRLoadConst(value=0, const_type="int"), LIRReturn()]
            lfn.body[1].dst_loc = ("r0", INT_TYPE)
            module.functions[lname] = lfn

        module.functions["main"] = main_fn
        backend = WasmGCBackend()
        wat = backend.compile(module)
        self.assertEqual(backend.lambda_table_indices["__lambda_0"], 0)
        self.assertEqual(backend.lambda_table_indices["__lambda_1"], 1)
        self.assertIn("(table 2 funcref)", wat)


# ============================================================
# IR 节点测试
# ============================================================

class TestIRNodes(unittest.TestCase):

    def test_ir_types(self):
        """测试预定义 IR 类型"""
        self.assertEqual(INT_TYPE.kind, IRType.INT)
        self.assertEqual(FLOAT_TYPE.kind, IRType.FLOAT)
        self.assertEqual(BOOL_TYPE.kind, IRType.BOOL)
        self.assertEqual(STRING_TYPE.kind, IRType.STRING)
        self.assertEqual(UNIT_TYPE.kind, IRType.UNIT)

    def test_ir_type_equality(self):
        """测试 IR 类型相等"""
        self.assertEqual(INT_TYPE, NovaType(IRType.INT))
        self.assertNotEqual(INT_TYPE, FLOAT_TYPE)

    def test_lir_module_repr(self):
        """测试 LIRModule 字符串表示"""
        module = LIRModule(name="test_mod")
        func = LIRFunction("main", [], UNIT_TYPE)
        module.functions["main"] = func
        text = repr(module)
        self.assertIn("test_mod", text)

    def test_hir_module_repr(self):
        """测试 HIRModule 字符串表示"""
        module = HIRModule(name="test_hir")
        text = repr(module)
        self.assertIn("test_hir", text)

    def test_mir_module_repr(self):
        """测试 MIRModule 字符串表示"""
        module = MIRModule(name="test_mir")
        text = repr(module)
        self.assertIn("test_mir", text)

    def test_lir_instructions(self):
        """测试 LIR 指令创建"""
        instr = LIRLoadConst(value=42, const_type="int")
        self.assertEqual(instr.value, 42)
        self.assertEqual(instr.const_type, "int")

        instr = LIRBinOp(op="+")
        self.assertEqual(instr.op, "+")

        instr = LIRReturn()
        self.assertIsInstance(instr, LIRInstr)


# ============================================================
# Pass 管理器测试
# ============================================================

class TestPassManager(unittest.TestCase):

    def test_default_pipeline(self):
        """测试默认优化管道"""
        from nova.ir.pass_manager import default_optimization_pipeline
        pm = default_optimization_pipeline()
        self.assertTrue(len(pm.hir_passes) > 0)
        self.assertTrue(len(pm.mir_passes) > 0)

    def test_pass_manager_run_hir(self):
        """测试 PassManager 运行 HIR passes"""
        from nova.ir.pass_manager import PassManager, ConstantFolding
        pm = PassManager()
        pm.add_hir_pass(ConstantFolding())
        module = HIRModule(name="test")
        pm.run_hir_passes(module)  # 不应抛出异常

    def test_pass_manager_run_mir(self):
        """测试 PassManager 运行 MIR passes"""
        from nova.ir.pass_manager import PassManager, CommonSubexprElimination
        pm = PassManager()
        pm.add_mir_pass(CommonSubexprElimination())
        module = MIRModule(name="test")
        pm.run_mir_passes(module)  # 不应抛出异常

    def test_pass_manager_run_lir(self):
        """测试 PassManager 运行 LIR passes"""
        from nova.ir.pass_manager import PassManager
        pm = PassManager()
        module = LIRModule(name="test")
        pm.run_lir_passes(module)  # 不应抛出异常


# ============================================================
# HIR/MIR/LIR 降级器测试
# ============================================================

class TestLowering(unittest.TestCase):

    def test_hir_lowering_basic(self):
        """测试基本 HIR 降级"""
        from nova.ir.hir_lowering import HIRLowering
        from nova.lexer import Lexer
        from nova.parser import Parser

        source = "fn add(a: Int, b: Int) -> Int { a + b }"
        tokens = Lexer(source).tokenize()
        ast = Parser(tokens).parse()

        hir = HIRLowering().lower(ast)
        self.assertEqual(hir.name, "main")

    def test_mir_lowering_basic(self):
        """测试基本 MIR 降级"""
        from nova.ir.hir_lowering import HIRLowering
        from nova.ir.mir_lowering import MIRLowering
        from nova.lexer import Lexer
        from nova.parser import Parser

        source = "fn add(a: Int, b: Int) -> Int { a + b }"
        tokens = Lexer(source).tokenize()
        ast = Parser(tokens).parse()

        hir = HIRLowering().lower(ast)
        mir = MIRLowering().lower(hir)
        self.assertIn("add", mir.functions)

    def test_lir_lowering_basic(self):
        """测试基本 LIR 降级"""
        from nova.ir.hir_lowering import HIRLowering
        from nova.ir.mir_lowering import MIRLowering
        from nova.ir.lir_lowering import LIRLowering
        from nova.lexer import Lexer
        from nova.parser import Parser

        source = "fn add(a: Int, b: Int) -> Int { a + b }"
        tokens = Lexer(source).tokenize()
        ast = Parser(tokens).parse()

        hir = HIRLowering().lower(ast)
        mir = MIRLowering().lower(hir)
        lir = LIRLowering().lower(mir)
        self.assertIn("add", lir.functions)
        self.assertTrue(len(lir.functions["add"].body) > 0)

    def test_lowering_with_main(self):
        """测试含 main 的完整降级"""
        from nova.ir.hir_lowering import HIRLowering
        from nova.ir.mir_lowering import MIRLowering
        from nova.ir.lir_lowering import LIRLowering
        from nova.lexer import Lexer
        from nova.parser import Parser

        source = 'fn main() -> Unit { print("Hello") }'
        tokens = Lexer(source).tokenize()
        ast = Parser(tokens).parse()

        hir = HIRLowering().lower(ast)
        mir = MIRLowering().lower(hir)
        lir = LIRLowering().lower(mir)
        self.assertIn("main", lir.functions)


# ============================================================
# C 后端闭包测试
# ============================================================

class TestCBackendClosure(unittest.TestCase):
    """C 后端闭包支持测试"""

    def _make_closure_lir_module(self):
        """创建包含闭包创建和调用的 LIR Module 用于测试"""
        from nova.ir.ir_nodes import (
            LIRModule, LIRFunction, LIRClosureCreate, LIRCallIndirect,
            LIRLabel, LIRLoadConst, LIRReturn, INT_TYPE, CLOSURE_TYPE,
        )

        module = LIRModule(name="test_closure")

        # main 函数：创建闭包并调用
        main_fn = LIRFunction(
            name="main",
            params=[],
            return_type=INT_TYPE,
        )
        main_fn.body = [
            LIRLabel(name="bb0"),
            LIRLoadConst(value=5, const_type="int"),       # r0 = 5 (捕获变量)
            LIRLoadConst(value=10, const_type="int"),      # r1 = 10 (用户参数)
            LIRClosureCreate(fn_name="__lambda_0", capture_count=1),  # r2 = closure
            LIRCallIndirect(arg_count=1),                  # r3 = closure(r1)
            LIRReturn(),
        ]
        # 设置位置
        main_fn.body[1].dst_loc = ("r0", INT_TYPE)
        main_fn.body[2].dst_loc = ("r1", INT_TYPE)
        main_fn.body[3].src_locs = [("r0", INT_TYPE)]
        main_fn.body[3].dst_loc = ("r2", CLOSURE_TYPE)
        main_fn.body[4].src_locs = [("r2", CLOSURE_TYPE), ("r1", INT_TYPE)]
        main_fn.body[4].dst_loc = ("r3", INT_TYPE)

        # lambda 函数
        lambda_fn = LIRFunction(
            name="__lambda_0",
            params=[("captured_n", INT_TYPE), ("x", INT_TYPE)],
            return_type=INT_TYPE,
        )
        lambda_fn.body = [
            LIRLabel(name="bb0"),
            LIRLoadConst(value=0, const_type="int"),  # placeholder
            LIRReturn(),
        ]
        lambda_fn.body[1].dst_loc = ("r0", INT_TYPE)

        module.functions["main"] = main_fn
        module.functions["__lambda_0"] = lambda_fn
        return module

    def test_closure_create_c_code(self):
        """LIRClosureCreate 应生成 nova_closure_new 调用"""
        from nova.backend.lir_c_backend import LIRCBackend

        module = self._make_closure_lir_module()
        backend = LIRCBackend()
        c_code = backend.compile(module)

        # 验证闭包创建
        self.assertIn("nova_closure_new", c_code)
        # 验证 trampoline 函数存在
        self.assertIn("nova_trampoline___lambda_0", c_code)
        # 验证捕获变量数组分配
        self.assertIn("nova_alloc", c_code)

    def test_closure_call_indirect_c_code(self):
        """LIRCallIndirect 应生成 nova_closure_call 调用"""
        from nova.backend.lir_c_backend import LIRCBackend

        module = self._make_closure_lir_module()
        backend = LIRCBackend()
        c_code = backend.compile(module)

        # 验证闭包间接调用
        self.assertIn("nova_closure_call", c_code)
        # 验证参数数组打包
        self.assertIn("nova_args_", c_code)

    def test_closure_source_to_c(self):
        """端到端：闭包源码应能正确编译为 C 代码"""
        source = """
            fn make_adder(n: Int) -> (Int) -> Int {
                |x: Int| -> Int { x + n }
            }
            fn main() -> Int {
                let add5 = make_adder(5)
                add5(10)
            }
        """
        lir = source_to_lir(source)

        from nova.backend.lir_c_backend import LIRCBackend
        backend = LIRCBackend()
        c_code = backend.compile(lir)

        # 验证闭包创建
        self.assertIn("nova_closure_new", c_code)
        # 验证闭包调用
        self.assertIn("nova_closure_call", c_code)
        # 验证 trampoline
        self.assertIn("nova_trampoline___lambda", c_code)
        # 验证 lambda 函数存在
        self.assertIn("nova_fn___lambda", c_code)
        # 验证 make_adder 返回闭包
        self.assertIn("NovaClosure*", c_code)

    @unittest.skipUnless(
        __import__("shutil").which("gcc"),
        "gcc not available"
    )
    def test_closure_c_code_compiles_with_gcc(self):
        """生成的闭包 C 代码应能通过 gcc 编译（语法检查）"""
        import subprocess
        import shutil

        source = """
            fn make_adder(n: Int) -> (Int) -> Int {
                |x: Int| -> Int { x + n }
            }
            fn main() -> Int {
                let add5 = make_adder(5)
                add5(10)
            }
        """
        lir = source_to_lir(source)

        from nova.backend.lir_c_backend import LIRCBackend
        backend = LIRCBackend()
        c_code = backend.compile(lir)

        runtime_dir = os.path.join(
            os.path.dirname(__file__), "..", "runtime"
        )

        with tempfile.NamedTemporaryFile(
            suffix=".c", mode="w", delete=False
        ) as f:
            f.write(c_code)
            f.flush()
            try:
                result = subprocess.run(
                    ["gcc", "-fsyntax-only", "-I", runtime_dir, f.name],
                    capture_output=True, text=True, timeout=10
                )
                # 允许警告，但不允许错误
                self.assertEqual(
                    result.returncode, 0,
                    f"GCC 编译失败: {result.stderr}"
                )
            finally:
                os.unlink(f.name)

    def test_closure_trampoline_double_return(self):
        """double 返回值的 trampoline 应使用 malloc+memcpy，而非 intptr_t 强转"""
        from nova.ir.ir_nodes import (
            LIRModule, LIRFunction, LIRClosureCreate, LIRCallIndirect,
            LIRLabel, LIRLoadConst, LIRReturn, FLOAT_TYPE, CLOSURE_TYPE,
        )
        from nova.backend.lir_c_backend import LIRCBackend

        module = LIRModule(name="test_closure_double")

        main_fn = LIRFunction(
            name="main", params=[], return_type=FLOAT_TYPE,
        )
        main_fn.body = [
            LIRLabel(name="bb0"),
            LIRLoadConst(value=3.14, const_type="float"),
            LIRClosureCreate(fn_name="__lambda_0", capture_count=1),
            LIRCallIndirect(arg_count=0),
            LIRReturn(),
        ]
        main_fn.body[1].dst_loc = ("r0", FLOAT_TYPE)
        main_fn.body[2].src_locs = [("r0", FLOAT_TYPE)]
        main_fn.body[2].dst_loc = ("r1", CLOSURE_TYPE)
        main_fn.body[3].src_locs = [("r1", CLOSURE_TYPE)]
        main_fn.body[3].dst_loc = ("r2", FLOAT_TYPE)

        lambda_fn = LIRFunction(
            name="__lambda_0",
            params=[("captured_f", FLOAT_TYPE)],
            return_type=FLOAT_TYPE,
        )
        lambda_fn.body = [
            LIRLabel(name="bb0"),
            LIRLoadConst(value=0.0, const_type="float"),
            LIRReturn(),
        ]
        lambda_fn.body[1].dst_loc = ("r0", FLOAT_TYPE)

        module.functions["main"] = main_fn
        module.functions["__lambda_0"] = lambda_fn

        backend = LIRCBackend()
        c_code = backend.compile(module)

        # 验证使用 malloc + memcpy 而非 intptr_t 强转
        self.assertIn("malloc(sizeof(double))", c_code)
        self.assertIn("memcpy(_nova_ret_ptr", c_code)
        # 确保不再出现危险的 intptr_t 强转 double
        self.assertNotIn("(intptr_t)", c_code)

    def test_mir_closure_call_is_indirect(self):
        """MIR 降级：闭包变量的调用应该是间接调用（SSA callee）"""
        from nova.ir.hir_lowering import HIRLowering
        from nova.ir.mir_lowering import MIRLowering
        from nova.lexer import Lexer
        from nova.parser import Parser
        from nova.type_checker import TypeChecker

        source = """
            fn make_adder(n: Int) -> (Int) -> Int {
                |x: Int| -> Int { x + n }
            }
            fn main() -> Int {
                let add5 = make_adder(5)
                add5(10)
            }
        """
        tokens = Lexer(source).tokenize()
        ast = Parser(tokens).parse()
        TypeChecker().check_program(ast)
        hir = HIRLowering().lower(ast)
        mir = MIRLowering().lower(hir)

        # main 函数中第二个 call (add5(10)) 的 callee 应该是 SSA 变量（如 v1）
        # 而不是字符串 "add5"
        main_fn = mir.functions["main"]
        call_count = 0
        for block in main_fn.basic_blocks:
            for instr in block.instructions:
                from nova.ir.ir_nodes import MIRCall
                if isinstance(instr, MIRCall):
                    call_count += 1
                    if call_count == 2:  # 第二个 call 是 add5(10)
                        # callee 应该是 SSA 变量名（以 v 开头），不是 "add5"
                        self.assertTrue(
                            instr.callee.startswith("v"),
                            f"闭包调用的 callee 应该是 SSA 变量，实际是: {instr.callee}"
                        )


if __name__ == "__main__":
    unittest.main()
