"""Nova IR 层 - 三层中间表示（HIR → MIR → LIR）

立即架构手术 A 进度（拆 ir/ir_nodes.py 上帝模块）：

- ✅ **A1**：通用类型系统已独立为 :mod:`~.ir_types`
- ✅ **A2（本轮）**：HIR / MIR / LIR 节点按层拆分到独立模块
- ⏳  **A3（下一轮）**：确认无外部依赖后 :mod:`~.ir_nodes` 变薄为 re-export

下游代码无需任何修改：所有 100+ 处对 ``nova.ir.ir_nodes`` 的导入
（IRType / NovaType / 各层节点等）通过兼容 re-export 层继续工作。

新代码推荐导入路径：
  - 类型相关 → ``from nova.ir.ir_types import ...``
  - HIR 节点   → ``from nova.ir.hir import HIR...``
  - MIR 节点   → ``from nova.ir.mir import MIR...``
  - LIR 节点   → ``from nova.ir.lir import LIR...``
  - 优化 Pass  → ``from nova.ir.pass_manager import ...``
  - IR 降级    → ``from nova.ir.hir_lowering import HIRLowering`` 等
"""

# 兼容 re-export：保持 `from nova.ir import IRType` 等旧用法可用
from .ir_types import (
    ADTType,
    BOOL_TYPE,
    CHAR_TYPE,
    CLOSURE_TYPE,
    FLOAT_TYPE,
    FnType,
    INT_TYPE,
    IRType,
    ListType,
    MapType,
    NEVER_TYPE,
    NovaType,
    OptionType,
    ResultType,
    STRING_TYPE,
    TupleType,
    UNIT_TYPE,
)

# A2 新增：HIR / MIR / LIR 节点顶层 re-export（新代码推荐路径）
from .hir import (
    HIRADTConstructor,
    HIRAliasDecl,
    HIRAssignExpr,
    HIRBinaryOp,
    HIRBindPattern,
    HIRBlockExpr,
    HIRBoolLiteral,
    HIRBoolPattern,
    HIRBreakExpr,
    HIRCallExpr,
    HIRCharLiteral,
    HIRCharPattern,
    HIRConstructorPattern,
    HIRContinueExpr,
    HIRDecl,
    HIRExportDecl,
    HIRFieldExpr,
    HIRFloatLiteral,
    HIRFloatPattern,
    HIRFnDecl,
    HIRForExpr,
    HIRFunction,
    HIRIdentifier,
    HIRIfExpr,
    HIRImportDecl,
    HIRIndexExpr,
    HIRIntLiteral,
    HIRIntPattern,
    HIRLambda,
    HIRLetDecl,
    HIRListComprehension,
    HIRListExpr,
    HIRListPattern,
    HIRMapExpr,
    HIRMatchArm,
    HIRMatchExpr,
    HIRModule,
    HIRPipeExpr,
    HIRPattern,
    HIRRangePattern,
    HIRRewriter,
    HIRStringLiteral,
    HIRStringPattern,
    HIRTupleExpr,
    HIRTuplePattern,
    HIRTypeDecl,
    HIRTypeDef,
    HIRUnaryOp,
    HIRUnitLiteral,
    HIRUnwrapExpr,
    HIRVariant,
    HIRVisitor,
    HIRWhileExpr,
    HIRWildcardPattern,
    _HIR_CHILD_FIELDS,
    _iter_hir_children,
)
from .lir import (
    LIRBinOp,
    LIRBranch,
    LIRBuildADT,
    LIRBuildList,
    LIRBuildMap,
    LIRBuildTuple,
    LIRCall,
    LIRCallIndirect,
    LIRClosureCreate,
    LIRData,
    LIRFieldAccess,
    LIRFunction,
    LIRGlobal,
    LIRIndex,
    LIRInstr,
    LIRJump,
    LIRLabel,
    LIRListAppend,
    LIRLoadConst,
    LIRLoadGlobal,
    LIRLoadReg,
    LIRModule,
    LIRPanic,
    LIRReturn,
    LIRStoreGlobal,
    LIRStoreReg,
    LIRSwitch,
    LIRUnaryOp,
)
from .mir import (
    MIRADTBuild,
    MIRBasicBlock,
    MIRBinOp,
    MIRBranch,
    MIRCall,
    MIRClosureCreate,
    MIRConst,
    MIRFieldAccess,
    MIRFunction,
    MIRGlobal,
    MIRIndexAccess,
    MIRInstruction,
    MIRJump,
    MIRListAppend,
    MIRListBuild,
    MIRLoad,
    MIRMapBuild,
    MIRMatchJump,
    MIRModule,
    MIRPanic,
    MIRPhi,
    MIRReturn,
    MIRStore,
    MIRSwitch,
    MIRTerminator,
    MIRTupleBuild,
    MIRUnaryOp,
)

__all__ = [
    # --- 类型系统（来自 ir_types）---
    "IRType",
    "NovaType",
    "INT_TYPE",
    "FLOAT_TYPE",
    "STRING_TYPE",
    "BOOL_TYPE",
    "CHAR_TYPE",
    "UNIT_TYPE",
    "NEVER_TYPE",
    "CLOSURE_TYPE",
    "ListType",
    "MapType",
    "TupleType",
    "FnType",
    "ADTType",
    "OptionType",
    "ResultType",
    # --- HIR 节点（来自 hir）---
    "HIRModule",
    "HIRFunction",
    "HIRTypeDef",
    "HIRVariant",
    "HIRDecl",
    "HIRFnDecl",
    "HIRLetDecl",
    "HIRTypeDecl",
    "HIRAliasDecl",
    "HIRImportDecl",
    "HIRExportDecl",
    "HIRExpr",
    "HIRIntLiteral",
    "HIRFloatLiteral",
    "HIRStringLiteral",
    "HIRBoolLiteral",
    "HIRCharLiteral",
    "HIRUnitLiteral",
    "HIRIdentifier",
    "HIRBinaryOp",
    "HIRUnaryOp",
    "HIRIfExpr",
    "HIRMatchExpr",
    "HIRMatchArm",
    "HIRPattern",
    "HIRIntPattern",
    "HIRFloatPattern",
    "HIRStringPattern",
    "HIRBoolPattern",
    "HIRCharPattern",
    "HIRWildcardPattern",
    "HIRBindPattern",
    "HIRConstructorPattern",
    "HIRRangePattern",
    "HIRTuplePattern",
    "HIRListPattern",
    "HIRLambda",
    "HIRCallExpr",
    "HIRPipeExpr",
    "HIRListExpr",
    "HIRTupleExpr",
    "HIRMapExpr",
    "HIRFieldExpr",
    "HIRIndexExpr",
    "HIRBlockExpr",
    "HIRForExpr",
    "HIRWhileExpr",
    "HIRBreakExpr",
    "HIRContinueExpr",
    "HIRListComprehension",
    "HIRADTConstructor",
    "HIRUnwrapExpr",
    "HIRAssignExpr",
    "_HIR_CHILD_FIELDS",
    "_iter_hir_children",
    "HIRVisitor",
    "HIRRewriter",
    # --- MIR 节点（来自 mir）---
    "MIRModule",
    "MIRFunction",
    "MIRBasicBlock",
    "MIRGlobal",
    "MIRInstruction",
    "MIRConst",
    "MIRLoad",
    "MIRStore",
    "MIRBinOp",
    "MIRUnaryOp",
    "MIRCall",
    "MIRClosureCreate",
    "MIRListBuild",
    "MIRListAppend",
    "MIRTupleBuild",
    "MIRMapBuild",
    "MIRADTBuild",
    "MIRFieldAccess",
    "MIRIndexAccess",
    "MIRPhi",
    "MIRTerminator",
    "MIRJump",
    "MIRBranch",
    "MIRReturn",
    "MIRSwitch",
    "MIRMatchJump",
    "MIRPanic",
    # --- LIR 节点（来自 lir）---
    "LIRModule",
    "LIRFunction",
    "LIRGlobal",
    "LIRData",
    "LIRInstr",
    "LIRLoadConst",
    "LIRLoadGlobal",
    "LIRStoreGlobal",
    "LIRLoadReg",
    "LIRStoreReg",
    "LIRBinOp",
    "LIRUnaryOp",
    "LIRCall",
    "LIRCallIndirect",
    "LIRJump",
    "LIRBranch",
    "LIRSwitch",
    "LIRReturn",
    "LIRLabel",
    "LIRIndex",
    "LIRFieldAccess",
    "LIRBuildList",
    "LIRListAppend",
    "LIRBuildMap",
    "LIRBuildTuple",
    "LIRBuildADT",
    "LIRClosureCreate",
    "LIRPanic",
    # --- 子模块 ---
    "ir_types",
    "hir",
    "mir",
    "lir",
    "ir_nodes",
    "hir_lowering",
    "mir_lowering",
    "lir_lowering",
    "pass_manager",
    "cfg_utils",
]
